Colour.find_or_create_by(slug: :belgian_blue_stone).update(name: 'Belgian Blue Stone', common: false)
Colour.find_or_create_by(slug: :black).update(name: 'black', common: true)
Colour.find_or_create_by(slug: :blue).update(name: 'blue', common: true)
Colour.find_or_create_by(slug: :brass).update(name: 'brass', common: false)
Colour.find_or_create_by(slug: :bronze).update(name: 'bronze', common: true)
Colour.find_or_create_by(slug: :brown).update(name: 'brown', common: false)
Colour.find_or_create_by(slug: :brushed_metal).update(name: 'brushed metal', common: false)
Colour.find_or_create_by(slug: :claret).update(name: 'claret', common: false)
Colour.find_or_create_by(slug: :clear).update(name: 'clear', common: false)
Colour.find_or_create_by(slug: :film_cell).update(name: 'film cell', common: false)
Colour.find_or_create_by(slug: :glass).update(name: 'glass', common: false)
Colour.find_or_create_by(slug: :gold).update(name: 'gold', common: false)
Colour.find_or_create_by(slug: :green).update(name: 'green', common: true)
Colour.find_or_create_by(slug: :green_and_red).update(name: 'green and red', common: false)
Colour.find_or_create_by(slug: :grey).update(name: 'grey', common: false)
Colour.find_or_create_by(slug: :marble).update(name: 'marble', common: true)
Colour.find_or_create_by(slug: :maroon).update(name: 'maroon', common: false)
Colour.find_or_create_by(slug: :multicoloured).update(name: 'multicoloured', common: false)
Colour.find_or_create_by(slug: :orange).update(name: 'orange', common: false)
Colour.find_or_create_by(slug: :pink).update(name: 'pink', common: false)
Colour.find_or_create_by(slug: :purple).update(name: 'purple', common: false)
Colour.find_or_create_by(slug: :purple_white_and_green).update(name: 'purple, white and green', common: false)
Colour.find_or_create_by(slug: :red).update(name: 'red', common: false)
Colour.find_or_create_by(slug: :red_and_black).update(name: 'red and black', common: false)
Colour.find_or_create_by(slug: :silver).update(name: 'silver', common: false)
Colour.find_or_create_by(slug: :slate).update(name: 'slate', common: false)
Colour.find_or_create_by(slug: :stone).update(name: 'stone', common: false)
Colour.find_or_create_by(slug: :terracotta).update(name: 'terracotta', common: false)
Colour.find_or_create_by(slug: :white).update(name: 'white', common: false)
Colour.find_or_create_by(slug: :wood).update(name: 'wood', common: false)
Colour.find_or_create_by(slug: :yellow).update(name: 'yellow', common: false)
