Country.find_or_create_by(alpha2: :ad).update(name: 'Andorra')
Country.find_or_create_by(alpha2: :ae).update(name: 'United Arab Emirates')
Country.find_or_create_by(alpha2: :af).update(name: 'Afghanistan')
Country.find_or_create_by(alpha2: :al).update(name: 'Albania')
Country.find_or_create_by(alpha2: :am).update(name: 'Armenia', latitude: 40.4934, longitude: 44.8556)
Country.find_or_create_by(alpha2: :ao).update(name: 'Angola', latitude: -12.5708, longitude: 17.7516)
Country.find_or_create_by(alpha2: :aq).update(name: 'Antarctica')
Country.find_or_create_by(alpha2: :ar).update(name: 'Argentina', latitude: -38.7278, longitude: -65.6838)
Country.find_or_create_by(alpha2: :at).update(name: 'Austria', latitude: 47.4574, longitude: 14.1332)
Country.find_or_create_by(alpha2: :au).update(name: 'Australia', latitude: -33.2679, longitude: 142.0824)
Country.find_or_create_by(alpha2: :aw).update(name: 'Aruba')
Country.find_or_create_by(alpha2: :az).update(name: 'Azerbaijan')
Country.find_or_create_by(alpha2: :bb).update(name: 'Barbados', latitude: 13.1585, longitude: -59.5625)
Country.find_or_create_by(alpha2: :bd).update(name: 'Bangladesh')
Country.find_or_create_by(alpha2: :be).update(name: 'Belgium', latitude: 50.8160, longitude: 4.3897)
Country.find_or_create_by(alpha2: :bg).update(name: 'Bulgaria', latitude: 41.9331, longitude: 25.5562)
Country.find_or_create_by(alpha2: :bh).update(name: 'Bahrain')
Country.find_or_create_by(alpha2: :bj).update(name: 'Benin')
Country.find_or_create_by(alpha2: :bl).update(name: 'Saint Barthélemy')
Country.find_or_create_by(alpha2: :bm).update(name: 'Bermuda')
Country.find_or_create_by(alpha2: :bo).update(name: 'Bolivia')
Country.find_or_create_by(alpha2: :bq).update(name: 'Bosnia and Herzegovina', latitude: 43.6935, longitude: 18.5896)
Country.find_or_create_by(alpha2: :br).update(name: 'Brazil', latitude: -16.9569, longitude: -51.8107)
Country.find_or_create_by(alpha2: :bs).update(name: 'Bahamas')
Country.find_or_create_by(alpha2: :bt).update(name: 'Bhutan')
Country.find_or_create_by(alpha2: :bw).update(name: 'Botswana')
Country.find_or_create_by(alpha2: :by).update(name: 'Belarus', latitude: 53.2153, longitude: 28.2297)
Country.find_or_create_by(alpha2: :bz).update(name: 'Belize')
Country.find_or_create_by(alpha2: :ca).update(name: 'Canada', latitude: 50.3388, longitude: -103.8516)
Country.find_or_create_by(alpha2: :cd).update(name: 'Democratic Republic of the Congo')
Country.find_or_create_by(alpha2: :cg).update(name: 'Republic of the Congo')
Country.find_or_create_by(alpha2: :ch).update(name: 'Switzerland', latitude: 46.7757, longitude: 8.3557)
Country.find_or_create_by(alpha2: :ci).update(name: 'Côte d\'Ivoire', latitude: 6.9781, longitude: -5.7412)
Country.find_or_create_by(alpha2: :cl).update(name: 'Chile', latitude: -32.5522, longitude: -71.4663)
Country.find_or_create_by(alpha2: :cm).update(name: 'Cameroon')
Country.find_or_create_by(alpha2: :cn).update(name: 'China', latitude: 30.6444, longitude: 104.0405)
Country.find_or_create_by(alpha2: :co).update(name: 'Colombia')
Country.find_or_create_by(alpha2: :cr).update(name: 'Costa Rica')
Country.find_or_create_by(alpha2: :cu).update(name: 'Cuba', latitude: 21.3389, longitude: -78.7646)
Country.find_or_create_by(alpha2: :cy).update(name: 'Cyprus')
Country.find_or_create_by(alpha2: :cz).update(name: 'Czech Republic', latitude: 49.3960, longitude: 15.5908)
Country.find_or_create_by(alpha2: :de).update(name: 'Germany', latitude: 50.2002, longitude: 10.4122)
Country.find_or_create_by(alpha2: :dk).update(name: 'Denmark', latitude: 55.6740, longitude: 9.6909)
Country.find_or_create_by(alpha2: :dm).update(name: 'Dominica')
Country.find_or_create_by(alpha2: :do).update(name: 'Dominican Republic')
Country.find_or_create_by(alpha2: :ec).update(name: 'Ecuador')
Country.find_or_create_by(alpha2: :ee).update(name: 'Estonia', latitude: 58.6597, longitude: 25.9621)
Country.find_or_create_by(alpha2: :eg).update(name: 'Egypt')
Country.find_or_create_by(alpha2: :eh).update(name: 'Western Sahara')
Country.find_or_create_by(alpha2: :es).update(name: 'Spain', latitude: 39.8567, longitude: -4.03402)
Country.find_or_create_by(alpha2: :et).update(name: 'Ethiopia')
Country.find_or_create_by(alpha2: :fi).update(name: 'Finland', latitude: 64.1784, longitude: 27.0011)
Country.find_or_create_by(alpha2: :fj).update(name: 'Fiji')
Country.find_or_create_by(alpha2: :fk).update(name: 'Falkland Islands')
Country.find_or_create_by(alpha2: :fo).update(name: 'Faroe Islands', latitude: 61.9768, longitude: -6.7850)
Country.find_or_create_by(alpha2: :fr).update(name: 'France', latitude: 46.4534, longitude: 3.2558)
Country.find_or_create_by(alpha2: :ga).update(name: 'Gabon')
Country.find_or_create_by(alpha2: :gb).update(name: 'United Kingdom', latitude: 52.1210, longitude: -1.3983)
Country.find_or_create_by(alpha2: :ge).update(name: 'Georgia', latitude: 41.9473, longitude: 43.8995)
Country.find_or_create_by(alpha2: :gg).update(name: 'Guernsey', latitude: 49.4591, longitude: -2.5646)
Country.find_or_create_by(alpha2: :gh).update(name: 'Ghana')
Country.find_or_create_by(alpha2: :gi).update(name: 'Gibraltar')
Country.find_or_create_by(alpha2: :gl).update(name: 'Greenland')
Country.find_or_create_by(alpha2: :gm).update(name: 'Gambia')
Country.find_or_create_by(alpha2: :gq).update(name: 'Equatorial Guinea')
Country.find_or_create_by(alpha2: :gr).update(name: 'Greece', latitude: 38.4713, longitude: 23.6005)
Country.find_or_create_by(alpha2: :hk).update(name: 'Hong Kong')
Country.find_or_create_by(alpha2: :hn).update(name: 'Honduras')
Country.find_or_create_by(alpha2: :hr).update(name: 'Croatia', latitude: 44.0424, longitude: 14.9100)
Country.find_or_create_by(alpha2: :ht).update(name: 'Haiti', latitude: 18.7186, longitude: -72.5488)
Country.find_or_create_by(alpha2: :hu).update(name: 'Hungary', latitude: 46.90727, longitude: 19.6917)
Country.find_or_create_by(alpha2: :id).update(name: 'Indonesia')
Country.find_or_create_by(alpha2: :ie).update(name: 'Ireland', latitude: 52.7968, longitude: -7.8370)
Country.find_or_create_by(alpha2: :il).update(name: 'Israel')
Country.find_or_create_by(alpha2: :im).update(name: 'Isle of Man', latitude: 54.1986, longitude: -4.5261)
Country.find_or_create_by(alpha2: :in).update(name: 'India', latitude: 19.2847, longitude: 78.5016)
Country.find_or_create_by(alpha2: :iq).update(name: 'Iraq')
Country.find_or_create_by(alpha2: :ir).update(name: 'Iran')
Country.find_or_create_by(alpha2: :is).update(name: 'Iceland', latitude: 64.9269, longitude: -18.5131)
Country.find_or_create_by(alpha2: :it).update(name: 'Italy', latitude: 41.9418, longitude: 13.8278)
Country.find_or_create_by(alpha2: :iw).update(name: 'International Waters')
Country.find_or_create_by(alpha2: :je).update(name: 'Jersey', latitude: 49.2080, longitude: -2.1277)
Country.find_or_create_by(alpha2: :jm).update(name: 'Jamaica', latitude: 18.1487, longitude: -77.2855)
Country.find_or_create_by(alpha2: :jo).update(name: 'Jordan')
Country.find_or_create_by(alpha2: :jp).update(name: 'Japan', latitude: 36.6655, longitude: 138.5775)
Country.find_or_create_by(alpha2: :ke).update(name: 'Kenya', latitude: 0.1540, longitude: 33.4099)
Country.find_or_create_by(alpha2: :kg).update(name: 'Kyrgyzstan')
Country.find_or_create_by(alpha2: :kh).update(name: 'Cambodia')
Country.find_or_create_by(alpha2: :ki).update(name: 'Kiribati')
Country.find_or_create_by(alpha2: :kn).update(name: 'Saint Kitts and Nevis')
Country.find_or_create_by(alpha2: :kp).update(name: 'North Korea')
Country.find_or_create_by(alpha2: :kr).update(name: 'South Korea')
Country.find_or_create_by(alpha2: :kw).update(name: 'Kuwait')
Country.find_or_create_by(alpha2: :kz).update(name: 'Kazakhstan')
Country.find_or_create_by(alpha2: :la).update(name: 'Laos')
Country.find_or_create_by(alpha2: :lb).update(name: 'Lebanon')
Country.find_or_create_by(alpha2: :lc).update(name: 'Saint Lucia', latitude: 13.8861, longitude: -60.9696)
Country.find_or_create_by(alpha2: :li).update(name: 'Liechtenstein')
Country.find_or_create_by(alpha2: :lk).update(name: 'Sri Lanka')
Country.find_or_create_by(alpha2: :lr).update(name: 'Liberia')
Country.find_or_create_by(alpha2: :ls).update(name: 'Lesotho')
Country.find_or_create_by(alpha2: :lt).update(name: 'Lithuania')
Country.find_or_create_by(alpha2: :lu).update(name: 'Luxembourg', latitude: 49.5730, longitude: 6.1557)
Country.find_or_create_by(alpha2: :lv).update(name: 'Latvia', latitude: 56.8568, longitude: 24.3368)
Country.find_or_create_by(alpha2: :ly).update(name: 'Libya')
Country.find_or_create_by(alpha2: :ma).update(name: 'Morocco')
Country.find_or_create_by(alpha2: :mc).update(name: 'Monaco', latitude: 43.7314, longitude: 7.4213)
Country.find_or_create_by(alpha2: :md).update(name: 'Moldova')
Country.find_or_create_by(alpha2: :me).update(name: 'Montenegro')
Country.find_or_create_by(alpha2: :mf).update(name: 'Saint Martin')
Country.find_or_create_by(alpha2: :mg).update(name: 'Madagascar')
Country.find_or_create_by(alpha2: :mk).update(name: 'Macedonia')
Country.find_or_create_by(alpha2: :ml).update(name: 'Mali')
Country.find_or_create_by(alpha2: :mm).update(name: 'Myanmar', latitude: 18.0250, longitude: 96.9552)
Country.find_or_create_by(alpha2: :mn).update(name: 'Mongolia')
Country.find_or_create_by(alpha2: :mo).update(name: 'Macao')
Country.find_or_create_by(alpha2: :mp).update(name: 'Northern Mariana Islands')
Country.find_or_create_by(alpha2: :mq).update(name: 'Martinique')
Country.find_or_create_by(alpha2: :mr).update(name: 'Mauritania')
Country.find_or_create_by(alpha2: :ms).update(name: 'Montserrat')
Country.find_or_create_by(alpha2: :mt).update(name: 'Malta', latitude: 35.8747, longitude: 14.5376)
Country.find_or_create_by(alpha2: :mu).update(name: 'Mauritius')
Country.find_or_create_by(alpha2: :mv).update(name: 'Maldives')
Country.find_or_create_by(alpha2: :mw).update(name: 'Malawi')
Country.find_or_create_by(alpha2: :mx).update(name: 'Mexico', latitude: 19.6797, longitude: -99.6274)
Country.find_or_create_by(alpha2: :my).update(name: 'Malaysia', latitude: 2.9358, longitude: 101.6898)
Country.find_or_create_by(alpha2: :mz).update(name: 'Mozambique')
Country.find_or_create_by(alpha2: :na).update(name: 'Namibia', latitude: -24.485, longitude: 15.8376)
Country.find_or_create_by(alpha2: :nc).update(name: 'New Caledonia')
Country.find_or_create_by(alpha2: :ne).update(name: 'Niger')
Country.find_or_create_by(alpha2: :nf).update(name: 'Norfolk Island')
Country.find_or_create_by(alpha2: :ng).update(name: 'Nigeria')
Country.find_or_create_by(alpha2: :ni).update(name: 'Nicaragua')
Country.find_or_create_by(alpha2: :nl).update(name: 'Netherlands', latitude: 52.1790, longitude: 5.3749)
Country.find_or_create_by(alpha2: :no).update(name: 'Norway', latitude: 58.9888, longitude: 6.1752)
Country.find_or_create_by(alpha2: :np).update(name: 'Nepal', latitude: 27.9476, longitude: 84.2740)
Country.find_or_create_by(alpha2: :nr).update(name: 'Nauru')
Country.find_or_create_by(alpha2: :nu).update(name: 'Niue')
Country.find_or_create_by(alpha2: :nz).update(name: 'New Zealand', latitude: -41.3483, longitude: 173.7109)
Country.find_or_create_by(alpha2: :om).update(name: 'Oman')
Country.find_or_create_by(alpha2: :pa).update(name: 'Panama')
Country.find_or_create_by(alpha2: :pe).update(name: 'Peru', latitude: -12.7800, longitude: -74.9634)
Country.find_or_create_by(alpha2: :pg).update(name: 'Papua New Guinea')
Country.find_or_create_by(alpha2: :ph).update(name: 'Philippines')
Country.find_or_create_by(alpha2: :pk).update(name: 'Pakistan', latitude: 31.3015, longitude: 74.2006)
Country.find_or_create_by(alpha2: :pl).update(name: 'Poland', latitude: 52.0590, longitude: 19.2040)
Country.find_or_create_by(alpha2: :pm).update(name: 'Saint Pierre and Miquelon')
Country.find_or_create_by(alpha2: :pn).update(name: 'Pitcairn')
Country.find_or_create_by(alpha2: :pr).update(name: 'Puerto Rico')
Country.find_or_create_by(alpha2: :ps).update(name: 'Palestine')
Country.find_or_create_by(alpha2: :pt).update(name: 'Portugal', latitude: 38.3949, longitude: -15.6105)
Country.find_or_create_by(alpha2: :pw).update(name: 'Palau')
Country.find_or_create_by(alpha2: :py).update(name: 'Paraguay')
Country.find_or_create_by(alpha2: :qa).update(name: 'Qatar')
Country.find_or_create_by(alpha2: :ro).update(name: 'Romania', latitude: 45.5997, longitude: 24.7361)
Country.find_or_create_by(alpha2: :rs).update(name: 'Serbia', latitude: 44.0235, longitude: 20.9220)
Country.find_or_create_by(alpha2: :ru).update(name: 'Russia', latitude: 58.0665, longitude: 38.3286)
Country.find_or_create_by(alpha2: :rw).update(name: 'Rwanda')
Country.find_or_create_by(alpha2: :sa).update(name: 'Saudi Arabia')
Country.find_or_create_by(alpha2: :sb).update(name: 'Solomon Islands')
Country.find_or_create_by(alpha2: :sc).update(name: 'Seychelles')
Country.find_or_create_by(alpha2: :sd).update(name: 'Sudan', latitude: 14.7619, longitude: 30.3136)
Country.find_or_create_by(alpha2: :se).update(name: 'Sweden', latitude: 59.3270, longitude: 18.1436)
Country.find_or_create_by(alpha2: :sg).update(name: 'Singapore', latitude: 1.3624, longitude: 103.8371)
Country.find_or_create_by(alpha2: :sh).update(name: 'Saint Helena, Ascension and Tristan da Cunha')
Country.find_or_create_by(alpha2: :si).update(name: 'Slovenia', latitude: 46.0234, longitude: 14.8567)
Country.find_or_create_by(alpha2: :sj).update(name: 'Svalbard and Jan Mayen')
Country.find_or_create_by(alpha2: :sk).update(name: 'Slovakia')
Country.find_or_create_by(alpha2: :sl).update(name: 'Sierra Leone')
Country.find_or_create_by(alpha2: :sm).update(name: 'San Marino')
Country.find_or_create_by(alpha2: :sn).update(name: 'Senegal')
Country.find_or_create_by(alpha2: :so).update(name: 'Somalia')
Country.find_or_create_by(alpha2: :sr).update(name: 'Suriname')
Country.find_or_create_by(alpha2: :ss).update(name: 'South Sudan')
Country.find_or_create_by(alpha2: :st).update(name: 'Sao Tome and Principe')
Country.find_or_create_by(alpha2: :sv).update(name: 'El Salvador')
Country.find_or_create_by(alpha2: :sy).update(name: 'Syria', latitude: 33.7276, longitude: 36.3730)
Country.find_or_create_by(alpha2: :sz).update(name: 'Swaziland')
Country.find_or_create_by(alpha2: :tc).update(name: 'Turks and Caicos Islands')
Country.find_or_create_by(alpha2: :tg).update(name: 'Togo')
Country.find_or_create_by(alpha2: :th).update(name: 'Thailand', latitude: 14.8721, longitude: 101.7337)
Country.find_or_create_by(alpha2: :tj).update(name: 'Tajikistan')
Country.find_or_create_by(alpha2: :tk).update(name: 'Tokelau')
Country.find_or_create_by(alpha2: :tl).update(name: 'Timor-Leste')
Country.find_or_create_by(alpha2: :tm).update(name: 'Turkmenistan')
Country.find_or_create_by(alpha2: :tn).update(name: 'Tunisia', latitude: 34.1213, longitude: 10.0519)
Country.find_or_create_by(alpha2: :to).update(name: 'Tonga', latitude: -19.9696, longitude: -174.6325)
Country.find_or_create_by(alpha2: :tr).update(name: 'Turkey', latitude: 38.7183, longitude: 35.4915)
Country.find_or_create_by(alpha2: :tt).update(name: 'Trinidad and Tobago')
Country.find_or_create_by(alpha2: :tv).update(name: 'Tuvalu')
Country.find_or_create_by(alpha2: :tw).update(name: 'Taiwan')
Country.find_or_create_by(alpha2: :tz).update(name: 'Tanzania')
Country.find_or_create_by(alpha2: :ua).update(name: 'Ukraine', latitude: 50.0768, longitude: 30.6589)
Country.find_or_create_by(alpha2: :ug).update(name: 'Uganda')
Country.find_or_create_by(alpha2: :us).update(name: 'United States', latitude: 40.8745, longitude: -97.9913)
Country.find_or_create_by(alpha2: :uy).update(name: 'Uruguay', latitude: -32.8837, longitude: -55.8566)
Country.find_or_create_by(alpha2: :uz).update(name: 'Uzbekistan')
Country.find_or_create_by(alpha2: :va).update(name: 'Vatican City')
Country.find_or_create_by(alpha2: :vc).update(name: 'Saint Vincent and the Grenadines')
Country.find_or_create_by(alpha2: :ve).update(name: 'Venezuela')
Country.find_or_create_by(alpha2: :vg).update(name: 'British Virgin Islands')
Country.find_or_create_by(alpha2: :vi).update(name: 'U.S. Virgin Islands')
Country.find_or_create_by(alpha2: :vn).update(name: 'Vietnam', latitude: 11.6770, longitude: 109.1811)
Country.find_or_create_by(alpha2: :vu).update(name: 'Vanuatu')
Country.find_or_create_by(alpha2: :wf).update(name: 'Wallis and Futuna')
Country.find_or_create_by(alpha2: :ws).update(name: 'Samoa')
Country.find_or_create_by(alpha2: :xk).update(name: 'Kosovo', latitude: 42.5744, longitude: 21.0285)
Country.find_or_create_by(alpha2: :xm).update(name: 'The Moon')
Country.find_or_create_by(alpha2: :ye).update(name: 'Yemen')
Country.find_or_create_by(alpha2: :yt).update(name: 'Mayotte')
Country.find_or_create_by(alpha2: :za).update(name: 'South Africa', latitude: -30.0819, longitude: 24.6584)
Country.find_or_create_by(alpha2: :zm).update(name: 'Zambia', latitude: -13.6147, longitude: 29.3975)
Country.find_or_create_by(alpha2: :zw).update(name: 'Zimbabwe')
