gb = Country.find_by!(alpha2: :gb)
Area.find_or_create_by(slug: :abbotskerswell).update(name: 'Abbotskerswell', country: gb, latitude: 50.5085, longitude: -3.61422)
Area.find_or_create_by(slug: :aberaeron).update(name: 'Aberaeron', country: gb)
Area.find_or_create_by(slug: :aberaman).update(name: 'Aberaman', country: gb, latitude: 51.7005, longitude: -3.4251)
Area.find_or_create_by(slug: :abercastle).update(name: 'Abercastle', country: gb, latitude: 51.95974, longitude: -5.12763)
Area.find_or_create_by(slug: :abercych).update(name: 'Abercych', country: gb, latitude: 52.03988, longitude: -4.55828)
Area.find_or_create_by(slug: :abercynon).update(name: 'Abercynon', country: gb, latitude: 51.6398, longitude: -3.33414)
Area.find_or_create_by(slug: :aberdare).update(name: 'Aberdare', country: gb, latitude: 51.71443, longitude: -3.44896)
Area.find_or_create_by(slug: :aberdaron).update(name: 'Aberdaron', country: gb, latitude: 52.80763, longitude: -4.72036)
Area.find_or_create_by(slug: :aberdeen).update(name: 'Aberdeen', country: gb, latitude: 57.14794, longitude: -2.10582)
Area.find_or_create_by(slug: :aberfeldy).update(name: 'Aberfeldy', country: gb, latitude: 56.6192, longitude: -3.86666)
Area.find_or_create_by(slug: :abergavenny).update(name: 'Abergavenny', country: gb, latitude: 51.82146, longitude: -3.01283)
Area.find_or_create_by(slug: :abergele).update(name: 'Abergele', country: gb, latitude: 53.28436, longitude: -3.58111)
Area.find_or_create_by(slug: :abernethy).update(name: 'Abernethy', country: gb, latitude: 51.20315, longitude: -2.19175)
Area.find_or_create_by(slug: :abertillery).update(name: 'Abertillery', country: gb, latitude: 51.73112, longitude: -3.1365)
Area.find_or_create_by(slug: :aberystwyth).update(name: 'Aberystwyth', country: gb, latitude: 52.41716, longitude: -4.07457)
Area.find_or_create_by(slug: :abingdon).update(name: 'Abingdon', country: gb, latitude: 51.67056, longitude: -1.28368)
Area.find_or_create_by(slug: :accrington).update(name: 'Accrington', country: gb, latitude: 53.75255, longitude: -2.36615)
Area.find_or_create_by(slug: :ackworth).update(name: 'Ackworth', country: gb, latitude: 53.65817, longitude: -1.32944)
Area.find_or_create_by(slug: :adderbury).update(name: 'Adderbury', country: gb, latitude: 52.01589, longitude: -1.32106)
Area.find_or_create_by(slug: :addingham).update(name: 'Addingham', country: gb, latitude: 53.94423, longitude: -1.88073)
Area.find_or_create_by(slug: :addiscombe).update(name: 'Addiscombe', country: gb, latitude: 51.37981, longitude: -0.06973)
Area.find_or_create_by(slug: :adpar).update(name: 'Adpar', country: gb, latitude: 52.0409, longitude: -4.46748)
Area.find_or_create_by(slug: :aith_shetland).update(name: 'Aith, Shetland', country: gb, latitude: 60.28635, longitude: -1.37553)
Area.find_or_create_by(slug: :albourne).update(name: 'Albourne', country: gb, latitude: 50.93648, longitude: -0.20114)
Area.find_or_create_by(slug: :albuquerque).update(name: 'Albuquerque', country: gb)
Area.find_or_create_by(slug: :alcester).update(name: 'Alcester', country: gb, latitude: 52.21683, longitude: -1.88672)
Area.find_or_create_by(slug: :aldborough).update(name: 'Aldborough', country: gb, latitude: 54.0918, longitude: -1.38146)
Area.find_or_create_by(slug: :aldbourne).update(name: 'Aldbourne', country: gb, latitude: 51.47728, longitude: -1.62752)
Area.find_or_create_by(slug: :aldeburgh).update(name: 'Aldeburgh', country: gb, latitude: 52.15278, longitude: 1.60141)
Area.find_or_create_by(slug: :alderley_edge).update(name: 'Alderley Edge', country: gb, latitude: 53.29729, longitude: -2.21255)
Area.find_or_create_by(slug: :alderney).update(name: 'Alderney', country: gb, latitude: 49.71471, longitude: -2.211)
Area.find_or_create_by(slug: :aldershot).update(name: 'Aldershot', country: gb, latitude: 51.2496, longitude: -0.75935)
Area.find_or_create_by(slug: :aldridge).update(name: 'Aldridge', country: gb, latitude: 52.60345, longitude: -1.90625)
Area.find_or_create_by(slug: :aldwick).update(name: 'Aldwick', country: gb, latitude: 50.78049, longitude: -0.70503)
Area.find_or_create_by(slug: :alfold).update(name: 'Alfold', country: gb)
Area.find_or_create_by(slug: :alford).update(name: 'Alford', country: gb, latitude: 53.2611, longitude: 0.17945)
Area.find_or_create_by(slug: :alfriston).update(name: 'Alfriston', country: gb, latitude: 50.80769, longitude: 0.1567)
Area.find_or_create_by(slug: :allerthorpe).update(name: 'Allerthorpe', country: gb, latitude: 53.9173, longitude: -0.80559)
Area.find_or_create_by(slug: :allesley).update(name: 'Allesley', country: gb)
Area.find_or_create_by(slug: :allestree).update(name: 'Allestree', country: gb, latitude: 52.95412, longitude: -1.48144)
Area.find_or_create_by(slug: :alloa).update(name: 'Alloa', country: gb)
Area.find_or_create_by(slug: :allonby).update(name: 'Allonby', country: gb)
Area.find_or_create_by(slug: :almington).update(name: 'Almington', country: gb, latitude: 52.91611, longitude: -2.44016)
Area.find_or_create_by(slug: :alnwick).update(name: 'Alnwick', country: gb, latitude: 55.41258, longitude: -1.70567)
Area.find_or_create_by(slug: :alton).update(name: 'Alton', country: gb, latitude: 51.14869, longitude: -0.97588)
Area.find_or_create_by(slug: :altrincham).update(name: 'Altrincham', country: gb, latitude: 53.3855, longitude: -2.35328)
Area.find_or_create_by(slug: :alum_bay).update(name: 'Alum Bay', country: gb, latitude: 50.6708, longitude: -1.5686)
Area.find_or_create_by(slug: :alwalton).update(name: 'Alwalton', country: gb, latitude: 52.54962, longitude: -0.32251)
Area.find_or_create_by(slug: :ambleside).update(name: 'Ambleside', country: gb, latitude: 54.43237, longitude: -2.96251)
Area.find_or_create_by(slug: :amersham).update(name: 'Amersham', country: gb, latitude: 51.67218, longitude: -0.64114)
Area.find_or_create_by(slug: :amesbury).update(name: 'Amesbury', country: gb)
Area.find_or_create_by(slug: :andover).update(name: 'Andover', country: gb, latitude: 51.20722, longitude: -1.47973)
Area.find_or_create_by(slug: :anglesey).update(name: 'Anglesey', country: gb, latitude: 53.22245, longitude: -4.17139)
Area.find_or_create_by(slug: :annan).update(name: 'Annan', country: gb, latitude: 54.98823, longitude: -3.25989)
Area.find_or_create_by(slug: :anstruther).update(name: 'Anstruther', country: gb, latitude: 56.22274, longitude: -2.69745)
Area.find_or_create_by(slug: :antrim).update(name: 'Antrim', country: gb, latitude: 54.71575, longitude: -6.21783)
Area.find_or_create_by(slug: :antrobus).update(name: 'Antrobus', country: gb, latitude: 53.31283, longitude: -2.53733)
Area.find_or_create_by(slug: :appleby_in_westmorland).update(name: 'Appleby-in-Westmorland', country: gb, latitude: 54.58005, longitude: -2.48658)
Area.find_or_create_by(slug: :appleford).update(name: 'Appleford', country: gb, latitude: 51.63955, longitude: -1.2359)
Area.find_or_create_by(slug: :arbuthnott).update(name: 'Arbuthnott', country: gb, latitude: 56.86922, longitude: -2.33021)
Area.find_or_create_by(slug: :ardglass).update(name: 'Ardglass', country: gb, latitude: 54.26018, longitude: -5.61091)
Area.find_or_create_by(slug: :ardingly).update(name: 'Ardingly', country: gb, latitude: 51.0784, longitude: -0.08411)
Area.find_or_create_by(slug: :arlesey).update(name: 'Arlesey', country: gb)
Area.find_or_create_by(slug: :armagh).update(name: 'Armagh', country: gb, latitude: 54.34781, longitude: -6.65627)
Area.find_or_create_by(slug: :arnipol).update(name: 'Arnipol', country: gb, latitude: 56.89213, longitude: -5.72954)
Area.find_or_create_by(slug: :arnold).update(name: 'Arnold', country: gb, latitude: 53.003, longitude: -1.13011)
Area.find_or_create_by(slug: :arnside).update(name: 'Arnside', country: gb, latitude: 54.20304, longitude: -2.83369)
Area.find_or_create_by(slug: :arundel).update(name: 'Arundel', country: gb, latitude: 50.85446, longitude: -0.55682)
Area.find_or_create_by(slug: :ascot).update(name: 'Ascot', country: gb, latitude: 51.41034, longitude: -0.67343)
Area.find_or_create_by(slug: :ascott_under_wychwood).update(name: 'Ascott-under-Wychwood', country: gb, latitude: 51.86622, longitude: -1.5633)
Area.find_or_create_by(slug: :ashbourne).update(name: 'Ashbourne', country: gb, latitude: 53.01717, longitude: -1.73302)
Area.find_or_create_by(slug: :ashburton).update(name: 'Ashburton', country: gb)
Area.find_or_create_by(slug: :ashby_de_la_zouch).update(name: 'Ashby-de-la-Zouch', country: gb, latitude: 52.74448, longitude: -1.47534)
Area.find_or_create_by(slug: :ashford).update(name: 'Ashford', country: gb, latitude: 51.14633, longitude: 0.86393)
Area.find_or_create_by(slug: :ashmansworth).update(name: 'Ashmansworth', country: gb, latitude: 51.31309, longitude: -1.40867)
Area.find_or_create_by(slug: :ashton_under_lyne).update(name: 'Ashton-under-Lyne', country: gb, latitude: 53.48616, longitude: -2.11152)
Area.find_or_create_by(slug: :aspatria).update(name: 'Aspatria', country: gb, latitude: 54.76438, longitude: -3.32685)
Area.find_or_create_by(slug: :aston).update(name: 'Aston', country: gb, latitude: 51.72499, longitude: -1.50764)
Area.find_or_create_by(slug: :atherstone).update(name: 'Atherstone', country: gb)
Area.find_or_create_by(slug: :attenborough).update(name: 'Attenborough', country: gb, latitude: 52.90413, longitude: -1.22993)
Area.find_or_create_by(slug: :auchterarder).update(name: 'Auchterarder', country: gb, latitude: 56.27577, longitude: -3.74316)
Area.find_or_create_by(slug: :audenshaw).update(name: 'Audenshaw', country: gb, latitude: 53.47037, longitude: -2.12354)
Area.find_or_create_by(slug: :augher).update(name: 'Augher', country: gb, latitude: 54.40864, longitude: -7.11962)
Area.find_or_create_by(slug: :auldearn).update(name: 'Auldearn', country: gb)
Area.find_or_create_by(slug: :aveley).update(name: 'Aveley', country: gb)
Area.find_or_create_by(slug: :axminster).update(name: 'Axminster', country: gb, latitude: 50.78162, longitude: -2.99833)
Area.find_or_create_by(slug: :aylesbury).update(name: 'Aylesbury', country: gb, latitude: 51.81541, longitude: -0.80958)
Area.find_or_create_by(slug: :aylesford).update(name: 'Aylesford', country: gb, latitude: 51.30411, longitude: 0.48331)
Area.find_or_create_by(slug: :aylsham).update(name: 'Aylsham', country: gb, latitude: 52.79249, longitude: 1.25244)
Area.find_or_create_by(slug: :ayr).update(name: 'Ayr', country: gb)
Area.find_or_create_by(slug: :aysgarth).update(name: 'Aysgarth', country: gb, latitude: 54.29082, longitude: -1.99438)
Area.find_or_create_by(slug: :backbarrow).update(name: 'Backbarrow', country: gb, latitude: 54.25178, longitude: -2.99207)
Area.find_or_create_by(slug: :badby).update(name: 'Badby', country: gb)
Area.find_or_create_by(slug: :baddesley_clinton).update(name: 'Baddesley Clinton', country: gb, latitude: 52.34333, longitude: -1.70707)
Area.find_or_create_by(slug: :baginton).update(name: 'Baginton', country: gb)
Area.find_or_create_by(slug: :bagshot).update(name: 'Bagshot', country: gb, latitude: 51.36154, longitude: -0.69254)
Area.find_or_create_by(slug: :baildon).update(name: 'Baildon', country: gb, latitude: 53.85349, longitude: -1.76715)
Area.find_or_create_by(slug: :bakewell).update(name: 'Bakewell', country: gb, latitude: 53.21503, longitude: -1.67576)
Area.find_or_create_by(slug: :bala).update(name: 'Bala', country: gb)
Area.find_or_create_by(slug: :balcombe).update(name: 'Balcombe', country: gb, latitude: 51.05785, longitude: -0.13252)
Area.find_or_create_by(slug: :balderton_newark_on_trent).update(name: 'Balderton, Newark-on-Trent', country: gb)
Area.find_or_create_by(slug: :ballycarry).update(name: 'Ballycarry', country: gb, latitude: 54.77078, longitude: -5.7512)
Area.find_or_create_by(slug: :ballycastle).update(name: 'Ballycastle', country: gb, latitude: 55.20532, longitude: -6.24006)
Area.find_or_create_by(slug: :ballyclare).update(name: 'Ballyclare', country: gb, latitude: 54.75225, longitude: -6.00124)
Area.find_or_create_by(slug: :ballykeel).update(name: 'Ballykeel', country: gb, latitude: 54.41367, longitude: -6.02187)
Area.find_or_create_by(slug: :ballykilbeg).update(name: 'Ballykilbeg', country: gb, latitude: 54.29727, longitude: -5.7723)
Area.find_or_create_by(slug: :ballymena).update(name: 'Ballymena', country: gb, latitude: 54.86474, longitude: -6.27704)
Area.find_or_create_by(slug: :ballymoney).update(name: 'Ballymoney', country: gb, latitude: 55.07005, longitude: -6.51847)
Area.find_or_create_by(slug: :ballynure).update(name: 'Ballynure', country: gb, latitude: 54.77307, longitude: -5.95116)
Area.find_or_create_by(slug: :ballyskeagh).update(name: 'Ballyskeagh', country: gb, latitude: 54.27392, longitude: -6.22743)
Area.find_or_create_by(slug: :balsall_common).update(name: 'Balsall Common', country: gb)
Area.find_or_create_by(slug: :bamber_bridge).update(name: 'Bamber Bridge', country: gb)
Area.find_or_create_by(slug: :bamburgh).update(name: 'Bamburgh', country: gb, latitude: 55.60907, longitude: -1.71017)
Area.find_or_create_by(slug: :banbridge).update(name: 'Banbridge', country: gb, latitude: 54.3515, longitude: -6.27126)
Area.find_or_create_by(slug: :banbury).update(name: 'Banbury', country: gb, latitude: 52.06125, longitude: -1.33956)
Area.find_or_create_by(slug: :banff).update(name: 'Banff', country: gb, latitude: 57.66472, longitude: -2.52243)
Area.find_or_create_by(slug: :bangor).update(name: 'Bangor, Gwynedd', country: gb, latitude: 53.21688, longitude: -4.10272)
Area.find_or_create_by(slug: :bangor_county_down).update(name: 'Bangor, County Down', country: gb, latitude: 54.66395, longitude: -5.66714)
Area.find_or_create_by(slug: :bannockburn).update(name: 'Bannockburn', country: gb, latitude: 56.09204, longitude: -3.91585)
Area.find_or_create_by(slug: :barcelona).update(name: 'Barcelona', country: gb)
Area.find_or_create_by(slug: :bardsey).update(name: 'Bardsey', country: gb, latitude: 53.8819, longitude: -1.44814)
Area.find_or_create_by(slug: :bargoed).update(name: 'Bargoed', country: gb, latitude: 51.68498, longitude: -3.24316)
Area.find_or_create_by(slug: :barmouth).update(name: 'Barmouth', country: gb, latitude: 52.71861, longitude: -4.05268)
Area.find_or_create_by(slug: :barnard_castle).update(name: 'Barnard Castle', country: gb, latitude: 54.54349, longitude: -1.92341)
Area.find_or_create_by(slug: :barnehurst).update(name: 'Barnehurst', country: gb, latitude: 51.46547, longitude: 0.15842)
Area.find_or_create_by(slug: :barnsley).update(name: 'Barnsley', country: gb, latitude: 53.55326, longitude: -1.48264)
Area.find_or_create_by(slug: :barnstaple).update(name: 'Barnstaple', country: gb, latitude: 51.07968, longitude: -4.05876)
Area.find_or_create_by(slug: :barra).update(name: 'Barra', country: gb, latitude: 56.9546, longitude: -7.48678)
Area.find_or_create_by(slug: :barrington).update(name: 'Barrington', country: gb)
Area.find_or_create_by(slug: :barrow_in_furness).update(name: 'Barrow-in-Furness', country: gb, latitude: 54.0938, longitude: -3.23969)
Area.find_or_create_by(slug: :barry).update(name: 'Barry', country: gb, latitude: 51.40469, longitude: -3.26895)
Area.find_or_create_by(slug: :barton).update(name: 'Barton', country: gb, latitude: 53.47566, longitude: -2.35415)
Area.find_or_create_by(slug: :barton_in_the_beans).update(name: 'Barton in the Beans', country: gb, latitude: 52.65429, longitude: -1.42096)
Area.find_or_create_by(slug: :barton_upon_humber).update(name: 'Barton-upon-Humber', country: gb, latitude: 53.68017, longitude: -0.44874)
Area.find_or_create_by(slug: :barwell).update(name: 'Barwell', country: gb, latitude: 52.5707, longitude: -1.35795)
Area.find_or_create_by(slug: :basildon).update(name: 'Basildon', country: gb, latitude: 51.56784, longitude: 0.42389)
Area.find_or_create_by(slug: :basingstoke).update(name: 'Basingstoke', country: gb, latitude: 51.26299, longitude: -1.08409)
Area.find_or_create_by(slug: :bath).update(name: 'Bath', country: gb, latitude: 51.38167, longitude: -2.35979)
Area.find_or_create_by(slug: :bathgate).update(name: 'Bathgate', country: gb)
Area.find_or_create_by(slug: :batley).update(name: 'Batley', country: gb, latitude: 53.71702, longitude: -1.63499)
Area.find_or_create_by(slug: :battle).update(name: 'Battle', country: gb, latitude: 50.91808, longitude: 0.48374)
Area.find_or_create_by(slug: :bawdsey).update(name: 'Bawdsey', country: gb, latitude: 51.98958, longitude: 1.39963)
Area.find_or_create_by(slug: :bawtry).update(name: 'Bawtry', country: gb)
Area.find_or_create_by(slug: :baxley_ga).update(name: 'Baxley, GA', country: gb)
Area.find_or_create_by(slug: :beacon_hill).update(name: 'Beacon Hill', country: gb, latitude: 51.12525, longitude: -0.74747)
Area.find_or_create_by(slug: :beaconsfield).update(name: 'Beaconsfield', country: gb, latitude: 51.60965, longitude: -0.65549)
Area.find_or_create_by(slug: :bealieu).update(name: 'Bealieu', country: gb)
Area.find_or_create_by(slug: :beaulieu).update(name: 'Beaulieu', country: gb, latitude: 50.81528, longitude: -1.45372)
Area.find_or_create_by(slug: :beaumaris).update(name: 'Beaumaris', country: gb, latitude: 53.26356, longitude: -4.09297)
Area.find_or_create_by(slug: :beccles).update(name: 'Beccles', country: gb, latitude: 52.45723, longitude: 1.56317)
Area.find_or_create_by(slug: :beckenham).update(name: 'Beckenham', country: gb, latitude: 51.40657, longitude: -0.02963)
Area.find_or_create_by(slug: :beckley).update(name: 'Beckley', country: gb, latitude: 51.79678, longitude: -1.18207)
Area.find_or_create_by(slug: :bedale).update(name: 'Bedale', country: gb, latitude: 54.28971, longitude: -1.5911)
Area.find_or_create_by(slug: :beddgelert).update(name: 'Beddgelert', country: gb, latitude: 53.0121, longitude: -4.10219)
Area.find_or_create_by(slug: :bedford).update(name: 'Bedford', country: gb, latitude: 52.13746, longitude: -0.47128)
Area.find_or_create_by(slug: :bedlington).update(name: 'Bedlington', country: gb, latitude: 55.13033, longitude: -1.59304)
Area.find_or_create_by(slug: :bedworth).update(name: 'Bedworth', country: gb, latitude: 52.48006, longitude: -1.47263)
Area.find_or_create_by(slug: :beeston).update(name: 'Beeston, Nottinghamshire', country: gb, latitude: 52.92612, longitude: -1.21089)
Area.find_or_create_by(slug: :beeston_beds).update(name: 'Beeston, Bedfordshire', country: gb, latitude: 52.11947, longitude: -0.29484)
Area.find_or_create_by(slug: :bekesbourne).update(name: 'Bekesbourne', country: gb, latitude: 51.25812, longitude: 1.14443)
Area.find_or_create_by(slug: :belbroughton).update(name: 'Belbroughton', country: gb, latitude: 52.39023, longitude: -2.11988)
Area.find_or_create_by(slug: :belchamp_walter).update(name: 'Belchamp Walter', country: gb, latitude: 52.03361, longitude: 0.65038)
Area.find_or_create_by(slug: :belfast).update(name: 'Belfast', country: gb, latitude: 54.59451, longitude: -5.92591)
Area.find_or_create_by(slug: :belford).update(name: 'Belford', country: gb, latitude: 55.59839, longitude: -1.82893)
Area.find_or_create_by(slug: :belper).update(name: 'Belper', country: gb, latitude: 53.02337, longitude: -1.4975)
Area.find_or_create_by(slug: :bembridge).update(name: 'Bembridge', country: gb, latitude: 50.68994, longitude: -1.08982)
Area.find_or_create_by(slug: :bempton).update(name: 'Bempton', country: gb, latitude: 54.13133, longitude: -0.17767)
Area.find_or_create_by(slug: :benson).update(name: 'Benson', country: gb, latitude: 51.6227, longitude: -1.10153)
Area.find_or_create_by(slug: :bentpath).update(name: 'Bentpath', country: gb, latitude: 55.2016, longitude: -3.08327)
Area.find_or_create_by(slug: :berkeley).update(name: 'Berkeley', country: gb, latitude: 51.692, longitude: -2.4596)
Area.find_or_create_by(slug: :berkhamsted).update(name: 'Berkhamsted', country: gb, latitude: 51.76062, longitude: -0.56301)
Area.find_or_create_by(slug: :berkswell).update(name: 'Berkswell', country: gb)
Area.find_or_create_by(slug: :berwickupontweed).update(name: 'Berwick-upon-Tweed', country: gb, latitude: 55.77084, longitude: -2.0076)
Area.find_or_create_by(slug: :besselsleigh).update(name: 'Besselsleigh', country: gb, latitude: 51.71301, longitude: -1.33592)
Area.find_or_create_by(slug: :betws_y_coed).update(name: 'Betws-y-Coed', country: gb, latitude: 53.05357, longitude: -3.84243)
Area.find_or_create_by(slug: :beverley).update(name: 'Beverley', country: gb, latitude: 53.84162, longitude: -0.42787)
Area.find_or_create_by(slug: :bewdley).update(name: 'Bewdley', country: gb, latitude: 52.3731, longitude: -2.31276)
Area.find_or_create_by(slug: :bexhill_on_sea).update(name: 'Bexhill-on-Sea', country: gb, latitude: 50.83862, longitude: 0.48127)
Area.find_or_create_by(slug: :bicester).update(name: 'Bicester', country: gb, latitude: 51.90344, longitude: -1.15052)
Area.find_or_create_by(slug: :bickleigh).update(name: 'Bickleigh', country: gb, latitude: 50.85095, longitude: -3.51188)
Area.find_or_create_by(slug: :bideford).update(name: 'Bideford', country: gb, latitude: 51.01782, longitude: -4.20546)
Area.find_or_create_by(slug: :biggar).update(name: 'Biggar', country: gb, latitude: 55.62509, longitude: -3.52322)
Area.find_or_create_by(slug: :biggleswade).update(name: 'Biggleswade', country: gb, latitude: 52.08721, longitude: -0.26422)
Area.find_or_create_by(slug: :bingham).update(name: 'Bingham', country: gb, latitude: 52.95077, longitude: -0.94782)
Area.find_or_create_by(slug: :bingley).update(name: 'Bingley', country: gb, latitude: 53.8515, longitude: -1.84113)
Area.find_or_create_by(slug: :birdham).update(name: 'Birdham', country: gb, latitude: 50.804, longitude: -0.82661)
Area.find_or_create_by(slug: :birkenhead).update(name: 'Birkenhead', country: gb, latitude: 53.39415, longitude: -3.01676)
Area.find_or_create_by(slug: :birmingham).update(name: 'Birmingham', country: gb, latitude: 52.46855, longitude: -1.90844)
Area.find_or_create_by(slug: :birstall).update(name: 'Birstall', country: gb, latitude: 53.74294, longitude: -1.66264)
Area.find_or_create_by(slug: :bishop_auckland).update(name: 'Bishop Auckland', country: gb, latitude: 54.66155, longitude: -1.67681)
Area.find_or_create_by(slug: :bishopsbourne).update(name: 'Bishopsbourne', country: gb, latitude: 51.2307, longitude: 1.1334)
Area.find_or_create_by(slug: :bishops_castle).update(name: 'Bishop\'s Castle', country: gb, latitude: 52.49226, longitude: -2.9977)
Area.find_or_create_by(slug: :bishops_stortford).update(name: 'Bishop\'s Stortford', country: gb, latitude: 51.86783, longitude: 0.16334)
Area.find_or_create_by(slug: :bishops_waltham).update(name: 'Bishop\'s Waltham', country: gb, latitude: 50.95462, longitude: -1.20951)
Area.find_or_create_by(slug: :blackburn).update(name: 'Blackburn', country: gb, latitude: 53.74857, longitude: -2.48315)
Area.find_or_create_by(slug: :blackbushe).update(name: 'Blackbushe', country: gb)
Area.find_or_create_by(slug: :blackheath).update(name: 'Blackheath', country: gb, latitude: 52.47441, longitude: -2.03764)
Area.find_or_create_by(slug: :black_notley).update(name: 'Black Notley', country: gb, latitude: 51.855, longitude: 0.53627)
Area.find_or_create_by(slug: :blackpool).update(name: 'Blackpool', country: gb, latitude: 53.81303, longitude: -3.05088)
Area.find_or_create_by(slug: :blaenau_ffestiniog).update(name: 'Blaenau Ffestiniog', country: gb, latitude: 52.99862, longitude: -3.94529)
Area.find_or_create_by(slug: :blaenclydach).update(name: 'Blaenclydach', country: gb, latitude: 51.6261, longitude: -3.46931)
Area.find_or_create_by(slug: :blairgowrie).update(name: 'Blairgowrie', country: gb, latitude: 56.59203, longitude: -3.33587)
Area.find_or_create_by(slug: :blakeney).update(name: 'Blakeney', country: gb, latitude: 52.95581, longitude: 1.01813)
Area.find_or_create_by(slug: :blandford_forum).update(name: 'Blandford Forum', country: gb, latitude: 50.85635, longitude: -2.16425)
Area.find_or_create_by(slug: :bletchley).update(name: 'Bletchley', country: gb, latitude: 51.99687, longitude: -0.74246)
Area.find_or_create_by(slug: :blewbury).update(name: 'Blewbury', country: gb, latitude: 51.56905, longitude: -1.23837)
Area.find_or_create_by(slug: :blisworth).update(name: 'Blisworth', country: gb)
Area.find_or_create_by(slug: :bloxwich).update(name: 'Bloxwich', country: gb, latitude: 52.61561, longitude: -1.99908)
Area.find_or_create_by(slug: :blyth).update(name: 'Blyth', country: gb, latitude: 55.12682, longitude: -1.51371)
Area.find_or_create_by(slug: :bodiam).update(name: 'Bodiam ', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :bodmin).update(name: 'Bodmin', country: gb, latitude: 50.46939, longitude: -4.71656)
Area.find_or_create_by(slug: :bognor_regis).update(name: 'Bognor Regis', country: gb, latitude: 50.78492, longitude: -0.6696)
Area.find_or_create_by(slug: :bolsover).update(name: 'Bolsover', country: gb, latitude: 53.22913, longitude: -1.29229)
Area.find_or_create_by(slug: :bolton).update(name: 'Bolton', country: gb, latitude: 53.57553, longitude: -2.41985)
Area.find_or_create_by(slug: :bolton_le_sands).update(name: 'Bolton-le-Sands', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :bo_ness).update(name: 'Bo\'Ness', country: gb, latitude: 56.0187, longitude: -3.60638)
Area.find_or_create_by(slug: :bootle_merseyside).update(name: 'Bootle, Merseyside', country: gb)
Area.find_or_create_by(slug: :borehamwood).update(name: 'Borehamwood', country: gb, latitude: 51.66092, longitude: -0.27539)
Area.find_or_create_by(slug: :boroughbridge).update(name: 'Boroughbridge', country: gb, latitude: 54.09627, longitude: -1.39642)
Area.find_or_create_by(slug: :borrowash).update(name: 'Borrowash', country: gb, latitude: 52.90542, longitude: -1.37463)
Area.find_or_create_by(slug: :borth).update(name: 'Borth', country: gb)
Area.find_or_create_by(slug: :bosham).update(name: 'Bosham', country: gb)
Area.find_or_create_by(slug: :boston).update(name: 'Boston', country: gb, latitude: 52.97744, longitude: -0.02398)
Area.find_or_create_by(slug: :boston_spa).update(name: 'Boston Spa', country: gb, latitude: 53.90461, longitude: -1.35982)
Area.find_or_create_by(slug: :bothwell).update(name: 'Bothwell', country: gb, latitude: 55.8001, longitude: -4.04567)
Area.find_or_create_by(slug: :bourne).update(name: 'Bourne', country: gb, latitude: 52.76801, longitude: -0.39642)
Area.find_or_create_by(slug: :bournemouth).update(name: 'Bournemouth', country: gb, latitude: 50.72168, longitude: -1.8709)
Area.find_or_create_by(slug: :bourton_on_the_water).update(name: 'Bourton-on-the-Water', country: gb, latitude: 51.88467, longitude: -1.75837)
Area.find_or_create_by(slug: :bowden).update(name: 'Bowden', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :bowdon).update(name: 'Bowdon', country: gb, latitude: 53.37809, longitude: -2.35866)
Area.find_or_create_by(slug: :box).update(name: 'Box', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :bracknell).update(name: 'Bracknell', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :bradford).update(name: 'Bradford', country: gb, latitude: 53.79476, longitude: -1.756)
Area.find_or_create_by(slug: :bradford_on_avon).update(name: 'Bradford on Avon', country: gb, latitude: 51.34577, longitude: -2.25399)
Area.find_or_create_by(slug: :bradninch).update(name: 'Bradninch', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :braemar).update(name: 'Braemar', country: gb)
Area.find_or_create_by(slug: :braes_of_foss).update(name: 'Braes of Foss', country: gb)
Area.find_or_create_by(slug: :braintree).update(name: 'Braintree', country: gb, latitude: 51.87844, longitude: 0.55306)
Area.find_or_create_by(slug: :bramcote).update(name: 'Bramcote', country: gb, latitude: 52.93445, longitude: -1.24689)
Area.find_or_create_by(slug: :bramley).update(name: 'Bramley', country: gb)
Area.find_or_create_by(slug: :brampton).update(name: 'Brampton', country: gb, latitude: 54.94275, longitude: -2.73434)
Area.find_or_create_by(slug: :braunston).update(name: 'Braunston', country: gb, latitude: 52.29129, longitude: -1.21237)
Area.find_or_create_by(slug: :brawby).update(name: 'Brawby', country: gb, latitude: 54.19247, longitude: -0.87509)
Area.find_or_create_by(slug: :brechin).update(name: 'Brechin', country: gb)
Area.find_or_create_by(slug: :brecon).update(name: 'Brecon', country: gb, latitude: 51.94673, longitude: -3.38899)
Area.find_or_create_by(slug: :bridestowe).update(name: 'Bridestowe', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :bridgeofallan).update(name: 'Bridge of Allan', country: gb, latitude: 56.15588, longitude: -3.94718)
Area.find_or_create_by(slug: :bridgnorth).update(name: 'Bridgnorth', country: gb, latitude: 52.53442, longitude: -2.41889)
Area.find_or_create_by(slug: :bridgwater).update(name: 'Bridgwater', country: gb, latitude: 51.12871, longitude: -3.00334)
Area.find_or_create_by(slug: :bridlington).update(name: 'Bridlington', country: gb, latitude: 54.0909, longitude: -0.19937)
Area.find_or_create_by(slug: :bridport).update(name: 'Bridport', country: gb, latitude: 50.73331, longitude: -2.75807)
Area.find_or_create_by(slug: :brighouse).update(name: 'Brighouse', country: gb, latitude: 53.70139, longitude: -1.78064)
Area.find_or_create_by(slug: :brighstone).update(name: 'Brighstone', country: gb, latitude: 50.64641, longitude: -1.39853)
Area.find_or_create_by(slug: :brighton).update(name: 'Brighton', country: gb, latitude: 50.82318, longitude: -0.13553)
Area.find_or_create_by(slug: :bristol).update(name: 'Bristol', country: gb, latitude: 51.45715, longitude: -2.59937)
Area.find_or_create_by(slug: :brixham).update(name: 'Brixham', country: gb, latitude: 50.39681, longitude: -3.51348)
Area.find_or_create_by(slug: :broad_campden).update(name: 'Broad Campden', country: gb)
Area.find_or_create_by(slug: :broadstairs).update(name: 'Broadstairs', country: gb, latitude: 51.35946, longitude: 1.43818)
Area.find_or_create_by(slug: :broadstone).update(name: 'Broadstone', country: gb)
Area.find_or_create_by(slug: :brockbridge).update(name: 'Brockbridge', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :brockenhouse).update(name: 'Brockenhouse', country: gb, latitude: 50.82257, longitude: -1.67576)
Area.find_or_create_by(slug: :brockham).update(name: 'Brockham', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :brockworth).update(name: 'Brockworth', country: gb)
Area.find_or_create_by(slug: :bromborough_pool).update(name: 'Bromborough Pool', country: gb)
Area.find_or_create_by(slug: :bromley).update(name: 'Bromley', country: gb, latitude: 51.40689, longitude: -0.00094)
Area.find_or_create_by(slug: :brompton_by_sawdon).update(name: 'Brompton-by-Sawdon', country: gb, latitude: 54.22398, longitude: -0.5561)
Area.find_or_create_by(slug: :bromsgrove).update(name: 'Bromsgrove', country: gb, latitude: 52.33848, longitude: -2.06568)
Area.find_or_create_by(slug: :bromyard).update(name: 'Bromyard', country: gb, latitude: 52.18721, longitude: -2.5065)
Area.find_or_create_by(slug: :brookwood_heath).update(name: 'Brookwood Heath', country: gb)
Area.find_or_create_by(slug: :broseley).update(name: 'Broseley', country: gb, latitude: 52.617, longitude: -2.48641)
Area.find_or_create_by(slug: :brotton).update(name: 'Brotton', country: gb, latitude: 54.5663, longitude: -0.93851)
Area.find_or_create_by(slug: :brough).update(name: 'Brough', country: gb)
Area.find_or_create_by(slug: :brough_of_birsay).update(name: 'Brough of Birsay', country: gb)
Area.find_or_create_by(slug: :broughshane).update(name: 'Broughshane', country: gb, latitude: 54.90486, longitude: -6.19996)
Area.find_or_create_by(slug: :broughton).update(name: 'Broughton', country: gb, latitude: 53.80991, longitude: -2.72362)
Area.find_or_create_by(slug: :broughty_ferry).update(name: 'Broughty Ferry', country: gb)
Area.find_or_create_by(slug: :brownhills).update(name: 'Brownhills', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :brynsiencyn).update(name: 'Brynsiencyn', country: gb)
Area.find_or_create_by(slug: :buckfastleigh).update(name: 'Buckfastleigh', country: gb, latitude: 50.48184, longitude: -3.77922)
Area.find_or_create_by(slug: :buckhaven).update(name: 'Buckhaven', country: gb)
Area.find_or_create_by(slug: :buckhurst_hill).update(name: 'Buckhurst Hill', country: gb, latitude: 51.62649, longitude: 0.02287)
Area.find_or_create_by(slug: :buckton).update(name: 'Buckton', country: gb, latitude: 54.1375, longitude: -0.1915)
Area.find_or_create_by(slug: :budapest).update(name: 'Budapest', country: gb)
Area.find_or_create_by(slug: :bude).update(name: 'Bude', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :budleigh_salterton).update(name: 'Budleigh Salterton', country: gb, latitude: 50.62986, longitude: -3.31925)
Area.find_or_create_by(slug: :builth_wells).update(name: 'Builth Wells', country: gb, latitude: 52.15153, longitude: -3.40743)
Area.find_or_create_by(slug: :bungay).update(name: 'Bungay', country: gb, latitude: 52.45658, longitude: 1.43582)
Area.find_or_create_by(slug: :burbage).update(name: 'Burbage', country: gb, latitude: 52.52642, longitude: -1.35144)
Area.find_or_create_by(slug: :burford).update(name: 'Burford', country: gb, latitude: 51.8096, longitude: -1.6344)
Area.find_or_create_by(slug: :burgess_hill).update(name: 'Burgess Hill', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :burgh_by_sands).update(name: 'Burgh by Sands', country: gb)
Area.find_or_create_by(slug: :burgh_island).update(name: 'Burgh Island', country: gb)
Area.find_or_create_by(slug: :burley_in_wharfedale).update(name: 'Burley-in-Wharfedale', country: gb, latitude: 53.91526, longitude: -1.74556)
Area.find_or_create_by(slug: :burley_woodhead).update(name: 'Burley Woodhead', country: gb)
Area.find_or_create_by(slug: :burnham_on_sea).update(name: 'Burnham-On-Sea', country: gb)
Area.find_or_create_by(slug: :burnham_overy_staithe).update(name: 'Burnham Overy Staithe', country: gb, latitude: 52.96275, longitude: 0.74585)
Area.find_or_create_by(slug: :burnham_thorpe).update(name: 'Burnham Thorpe', country: gb, latitude: 52.93035, longitude: 0.76006)
Area.find_or_create_by(slug: :burnley).update(name: 'Burnley', country: gb, latitude: 53.78641, longitude: -2.22935)
Area.find_or_create_by(slug: :burnsall).update(name: 'Burnsall', country: gb)
Area.find_or_create_by(slug: :burntisland).update(name: 'Burntisland', country: gb, latitude: 56.05903, longitude: -3.23297)
Area.find_or_create_by(slug: :burntwood).update(name: 'Burntwood', country: gb, latitude: 52.679, longitude: -1.90727)
Area.find_or_create_by(slug: :burra_beach_shetland).update(name: 'Burra Beach, Shetland', country: gb, latitude: 60.06067, longitude: -1.35972)
Area.find_or_create_by(slug: :burrough_on_the_hill).update(name: 'Burrough on The Hill', country: gb)
Area.find_or_create_by(slug: :burry_port).update(name: 'Burry Port', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :burton_in_kendal).update(name: 'Burton-in-Kendal', country: gb)
Area.find_or_create_by(slug: :burton_upon_trent).update(name: 'Burton-upon-Trent', country: gb, latitude: 52.80339, longitude: -1.63414)
Area.find_or_create_by(slug: :burwash).update(name: 'Burwash', country: gb, latitude: 50.99762, longitude: 0.38557)
Area.find_or_create_by(slug: :burwell).update(name: 'Burwell', country: gb, latitude: 52.27225, longitude: 0.32388)
Area.find_or_create_by(slug: :bury).update(name: 'Bury', country: gb, latitude: 53.59951, longitude: -2.30354)
Area.find_or_create_by(slug: :bury_st_edmunds).update(name: 'Bury St Edmunds', country: gb, latitude: 52.24408, longitude: 0.71647)
Area.find_or_create_by(slug: :bury_west_sussex).update(name: 'Bury, West Sussex', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :bushey).update(name: 'Bushey', country: gb, latitude: 51.6499, longitude: -0.3942)
Area.find_or_create_by(slug: :buttermere).update(name: 'Buttermere', country: gb, latitude: 54.54175, longitude: -3.27521)
Area.find_or_create_by(slug: :buxton).update(name: 'Buxton', country: gb, latitude: 53.25977, longitude: -1.91978)
Area.find_or_create_by(slug: :buxworth).update(name: 'Buxworth', country: gb, latitude: 53.33534, longitude: -1.96772)
Area.find_or_create_by(slug: :byfield).update(name: 'Byfield', country: gb, latitude: 52.17373, longitude: -1.24485)
Area.find_or_create_by(slug: :caerleon).update(name: 'Caerleon', country: gb, latitude: 51.60919, longitude: -2.95365)
Area.find_or_create_by(slug: :caernarfon).update(name: 'Caernarfon', country: gb, latitude: 53.13965, longitude: -4.27681)
Area.find_or_create_by(slug: :calbourne).update(name: 'Calbourne', country: gb, latitude: 50.67824, longitude: -1.39985)
Area.find_or_create_by(slug: :calderdale).update(name: 'Calderdale', country: gb)
Area.find_or_create_by(slug: :caldy_wirral).update(name: 'Caldy. Wirral', country: gb)
Area.find_or_create_by(slug: :calne).update(name: 'Calne', country: gb, latitude: 51.43746, longitude: -2.00402)
Area.find_or_create_by(slug: :calshot).update(name: 'Calshot', country: gb, latitude: 50.8084, longitude: -1.3182)
Area.find_or_create_by(slug: :calstock).update(name: 'Calstock', country: gb)
Area.find_or_create_by(slug: :calver).update(name: 'Calver', country: gb, latitude: 53.26831, longitude: -1.63092)
Area.find_or_create_by(slug: :camberley).update(name: 'Camberley', country: gb, latitude: 51.3343, longitude: -0.76712)
Area.find_or_create_by(slug: :cambridge).update(name: 'Cambridge', country: gb, latitude: 52.20323, longitude: 0.1189)
Area.find_or_create_by(slug: :camghouran).update(name: 'Camghouran', country: gb)
Area.find_or_create_by(slug: :campbeltown).update(name: 'Campbeltown', country: gb, latitude: 55.42504, longitude: -5.61352)
Area.find_or_create_by(slug: :cannock).update(name: 'Cannock', country: gb, latitude: 52.68848, longitude: -2.03217)
Area.find_or_create_by(slug: :canons_ashby).update(name: 'Canons Ashby', country: gb, latitude: 52.15115, longitude: -1.15778)
Area.find_or_create_by(slug: :canterbury).update(name: 'Canterbury', country: gb, latitude: 51.27165, longitude: 1.08454)
Area.find_or_create_by(slug: :canvey_island).update(name: 'Canvey Island', country: gb)
Area.find_or_create_by(slug: :capernwray).update(name: 'Capernwray', country: gb, latitude: 54.14096, longitude: -2.72093)
Area.find_or_create_by(slug: :cardiff).update(name: 'Cardiff', country: gb, latitude: 51.49107, longitude: -3.19251)
Area.find_or_create_by(slug: :cardigan).update(name: 'Cardigan', country: gb, latitude: 52.08504, longitude: -4.66577)
Area.find_or_create_by(slug: :carlisle).update(name: 'Carlisle', country: gb, latitude: 54.89187, longitude: -2.93323)
Area.find_or_create_by(slug: :carlton).update(name: 'Carlton', country: gb, latitude: 53.73969, longitude: -1.49404)
Area.find_or_create_by(slug: :carmarthen).update(name: 'Carmarthen', country: gb, latitude: 51.85658, longitude: -4.30835)
Area.find_or_create_by(slug: :carndonagh).update(name: 'Carndonagh', country: gb)
Area.find_or_create_by(slug: :carnforth).update(name: 'Carnforth', country: gb, latitude: 54.12975, longitude: -2.7711)
Area.find_or_create_by(slug: :carnkie).update(name: 'Carnkie', country: gb)
Area.find_or_create_by(slug: :carnlough).update(name: 'Carnlough', country: gb, latitude: 54.9847, longitude: -5.9927)
Area.find_or_create_by(slug: :carnmoney).update(name: 'Carnmoney', country: gb, latitude: 54.67871, longitude: -5.96238)
Area.find_or_create_by(slug: :carrickfergus).update(name: 'Carrickfergus', country: gb, latitude: 54.71749, longitude: -5.80881)
Area.find_or_create_by(slug: :carterton).update(name: 'Carterton', country: gb, latitude: 51.75833, longitude: -1.59632)
Area.find_or_create_by(slug: :cartmel).update(name: 'Cartmel', country: gb, latitude: 54.20117, longitude: -2.9544)
Area.find_or_create_by(slug: :castle_cary).update(name: 'Castle Cary', country: gb, latitude: 51.09014, longitude: -2.51057)
Area.find_or_create_by(slug: :castle_douglas).update(name: 'Castle Douglas', country: gb)
Area.find_or_create_by(slug: :castleford).update(name: 'Castleford', country: gb, latitude: 53.72715, longitude: -1.35084)
Area.find_or_create_by(slug: :castle_hedingham).update(name: 'Castle Hedingham', country: gb, latitude: 51.98992, longitude: 0.59922)
Area.find_or_create_by(slug: :castle_howard).update(name: 'Castle Howard', country: gb)
Area.find_or_create_by(slug: :castlewellan).update(name: 'Castlewellan', country: gb, latitude: 54.26462, longitude: -5.95618)
Area.find_or_create_by(slug: :caterham).update(name: 'Caterham', country: gb, latitude: 51.28311, longitude: -0.08133)
Area.find_or_create_by(slug: :catterline).update(name: 'Catterline', country: gb)
Area.find_or_create_by(slug: :caversham).update(name: 'Caversham', country: gb, latitude: 51.46826, longitude: -0.97961)
Area.find_or_create_by(slug: :cawthorne).update(name: 'Cawthorne', country: gb)
Area.find_or_create_by(slug: :cellardyke).update(name: 'Cellardyke', country: gb)
Area.find_or_create_by(slug: :chalfont_st_peter).update(name: 'Chalfont St Peter', country: gb, latitude: 51.60633, longitude: -0.55667)
Area.find_or_create_by(slug: :chalton).update(name: 'Chalton', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :chapmanslade).update(name: 'Chapmanslade', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :chard).update(name: 'Chard', country: gb, latitude: 50.87214, longitude: -2.9658)
Area.find_or_create_by(slug: :charing).update(name: 'Charing', country: gb, latitude: 51.21123, longitude: 0.79408)
Area.find_or_create_by(slug: :charlbury).update(name: 'Charlbury', country: gb, latitude: 51.87326, longitude: -1.48364)
Area.find_or_create_by(slug: :charlton_mackrell).update(name: 'Charlton Mackrell', country: gb, latitude: 51.036, longitude: -2.66826)
Area.find_or_create_by(slug: :charmouth).update(name: 'Charmouth', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :chartwell).update(name: 'Chartwell', country: gb)
Area.find_or_create_by(slug: :chase_terrace).update(name: 'Chase Terrace', country: gb, latitude: 52.68397, longitude: -1.93399)
Area.find_or_create_by(slug: :chasetown).update(name: 'Chasetown', country: gb, latitude: 52.67131, longitude: -1.93542)
Area.find_or_create_by(slug: :chatham).update(name: 'Chatham', country: gb, latitude: 51.38721, longitude: 0.52379)
Area.find_or_create_by(slug: :chatterton).update(name: 'Chatterton', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :chawton).update(name: 'Chawton', country: gb, latitude: 51.1337, longitude: -0.98884)
Area.find_or_create_by(slug: :cheadle).update(name: 'Cheadle', country: gb)
Area.find_or_create_by(slug: :cheam).update(name: 'Cheam', country: gb, latitude: 51.35816, longitude: -0.21333)
Area.find_or_create_by(slug: :chelmsford).update(name: 'Chelmsford', country: gb, latitude: 51.73365, longitude: 0.47423)
Area.find_or_create_by(slug: :chelsfield).update(name: 'Chelsfield', country: gb, latitude: 51.3555, longitude: 0.12531)
Area.find_or_create_by(slug: :chelsham).update(name: 'Chelsham', country: gb, latitude: 51.30754, longitude: -0.04367)
Area.find_or_create_by(slug: :cheltenham).update(name: 'Cheltenham', country: gb, latitude: 51.89373, longitude: -2.08057)
Area.find_or_create_by(slug: :chepstow).update(name: 'Chepstow', country: gb, latitude: 51.63611, longitude: -2.67022)
Area.find_or_create_by(slug: :cheriton).update(name: 'Cheriton', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :cheshunt).update(name: 'Cheshunt', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :chester).update(name: 'Chester', country: gb, latitude: 53.19141, longitude: -2.89297)
Area.find_or_create_by(slug: :chesterfield).update(name: 'Chesterfield', country: gb, latitude: 53.23665, longitude: -1.42731)
Area.find_or_create_by(slug: :chesterton).update(name: 'Chesterton', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :chicester).update(name: 'Chicester', country: gb)
Area.find_or_create_by(slug: :chichester).update(name: 'Chichester', country: gb, latitude: 50.83635, longitude: -0.77821)
Area.find_or_create_by(slug: :chiddingly).update(name: 'Chiddlingly', country: gb, latitude: 50.8995, longitude: 0.19862)
Area.find_or_create_by(slug: :chilton).update(name: 'Chilton', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :chilwell).update(name: 'Chilwell', country: gb, latitude: 52.91815, longitude: -1.2311)
Area.find_or_create_by(slug: :chingford).update(name: 'Chingford', country: gb, latitude: 51.62996, longitude: 0.00099)
Area.find_or_create_by(slug: :chinnor).update(name: 'Chinnor', country: gb)
Area.find_or_create_by(slug: :chippenham).update(name: 'Chippenham', country: gb, latitude: 51.45812, longitude: -2.12012)
Area.find_or_create_by(slug: :chipping_campden).update(name: 'Chipping Campden', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :chipping_norton).update(name: 'Chipping Norton', country: gb, latitude: 51.94157, longitude: -1.54358)
Area.find_or_create_by(slug: :chislehurst).update(name: 'Chislehurst', country: gb, latitude: 51.41041, longitude: 0.06789)
Area.find_or_create_by(slug: :chorley).update(name: 'Chorley', country: gb)
Area.find_or_create_by(slug: :christchurch).update(name: 'Christchurch', country: gb, latitude: 50.73357, longitude: -1.77618)
Area.find_or_create_by(slug: :chulmleigh).update(name: 'Chulmleigh', country: gb)
Area.find_or_create_by(slug: :church_langton).update(name: 'Church Langton', country: gb, latitude: 52.5339, longitude: -0.93231)
Area.find_or_create_by(slug: :church_norton).update(name: 'Church Norton', country: gb, latitude: 50.75104, longitude: -0.77407)
Area.find_or_create_by(slug: :cirencester).update(name: 'Cirencester', country: gb, latitude: 51.71665, longitude: -1.9696)
Area.find_or_create_by(slug: :clacton_on_sea).update(name: 'Clacton-on-Sea', country: gb)
Area.find_or_create_by(slug: :clanfield).update(name: 'Clanfield', country: gb, latitude: 50.94958, longitude: -0.99557)
Area.find_or_create_by(slug: :claughton).update(name: 'Claughton', country: gb, latitude: 54.0897, longitude: -2.67477)
Area.find_or_create_by(slug: :claydon).update(name: 'Claydon', country: gb, latitude: 52.14668, longitude: -1.33322)
Area.find_or_create_by(slug: :cleadon).update(name: 'Cleadon', country: gb, latitude: 54.95522, longitude: -1.4006)
Area.find_or_create_by(slug: :cleethorpes).update(name: 'Cleethorpes', country: gb, latitude: 53.55732, longitude: -0.02575)
Area.find_or_create_by(slug: :clemson).update(name: 'Clemson', country: gb)
Area.find_or_create_by(slug: :clevedon).update(name: 'Clevedon', country: gb, latitude: 51.43683, longitude: -2.85367)
Area.find_or_create_by(slug: :clevedon_north_somerset).update(name: 'Clevedon, North Somerset', country: gb, latitude: 51.44052, longitude: -2.85816)
Area.find_or_create_by(slug: :cliffe_woods).update(name: 'Cliffe Woods', country: gb)
Area.find_or_create_by(slug: :climping).update(name: 'Climping', country: gb, latitude: 50.80488, longitude: -0.58097)
Area.find_or_create_by(slug: :clitheroe).update(name: 'Clitheroe', country: gb, latitude: 53.87216, longitude: -2.39172)
Area.find_or_create_by(slug: :clovelly).update(name: 'Clovelly', country: gb, latitude: 50.99796, longitude: -4.39901)
Area.find_or_create_by(slug: :clun).update(name: 'Clun', country: gb)
Area.find_or_create_by(slug: :clynder).update(name: 'Clynder', country: gb)
Area.find_or_create_by(slug: :clyst_honiton).update(name: 'Clyst Honiton', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :coalbrookdale).update(name: 'Coalbrookdale', country: gb, latitude: 52.64021, longitude: -2.49279)
Area.find_or_create_by(slug: :coalisland).update(name: 'Coalisland', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :coalville).update(name: 'Coalville', country: gb, latitude: 52.72223, longitude: -1.37122)
Area.find_or_create_by(slug: :cobham).update(name: 'Cobham', country: gb, latitude: 51.32606, longitude: -0.40877)
Area.find_or_create_by(slug: :cockermouth).update(name: 'Cockermouth', country: gb, latitude: 54.66309, longitude: -3.36407)
Area.find_or_create_by(slug: :coggeshall).update(name: 'Coggeshall', country: gb, latitude: 51.87077, longitude: 0.68535)
Area.find_or_create_by(slug: :colchester).update(name: 'Colchester', country: gb, latitude: 51.88936, longitude: 0.86891)
Area.find_or_create_by(slug: :cold_ashby).update(name: 'Cold Ashby', country: gb, latitude: 52.38355, longitude: -1.05493)
Area.find_or_create_by(slug: :coldingham).update(name: 'Coldingham', country: gb, latitude: 55.88661, longitude: -2.156)
Area.find_or_create_by(slug: :coldstream).update(name: 'Coldstream', country: gb, latitude: 55.65132, longitude: -2.2534)
Area.find_or_create_by(slug: :coleford).update(name: 'Coleford', country: gb)
Area.find_or_create_by(slug: :coleraine).update(name: 'Coleraine', country: gb, latitude: 55.16724, longitude: -6.6579)
Area.find_or_create_by(slug: :coleshill).update(name: 'Coleshill', country: gb, latitude: 52.49941, longitude: -1.70551)
Area.find_or_create_by(slug: :colne).update(name: 'Colne', country: gb, latitude: 53.85514, longitude: -2.17912)
Area.find_or_create_by(slug: :colne_engaine).update(name: 'Colne Engaine', country: gb)
Area.find_or_create_by(slug: :colwall).update(name: 'Colwall', country: gb)
Area.find_or_create_by(slug: :colyton).update(name: 'Colyton', country: gb, latitude: 50.74012, longitude: -3.07016)
Area.find_or_create_by(slug: :comber).update(name: 'Comber', country: gb, latitude: 54.5493, longitude: -5.74833)
Area.find_or_create_by(slug: :combwich).update(name: 'Combwich', country: gb, latitude: 51.1756, longitude: -3.0595)
Area.find_or_create_by(slug: :compton).update(name: 'Compton', country: gb)
Area.find_or_create_by(slug: :coneysthorpe).update(name: 'Coneysthorpe', country: gb, latitude: 54.13316, longitude: -0.91136)
Area.find_or_create_by(slug: :congleton).update(name: 'Congleton', country: gb, latitude: 53.16622, longitude: -2.20611)
Area.find_or_create_by(slug: :coningsby).update(name: 'Coningsby', country: gb, latitude: 53.09614, longitude: -0.1763)
Area.find_or_create_by(slug: :coniston).update(name: 'Coniston', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :consett).update(name: 'Consett', country: gb)
Area.find_or_create_by(slug: :conwy).update(name: 'Conwy', country: gb, latitude: 53.28057, longitude: -3.82386)
Area.find_or_create_by(slug: :cookham).update(name: 'Cookham', country: gb, latitude: 51.55998, longitude: -0.74081)
Area.find_or_create_by(slug: :cookstown).update(name: 'Cookstown', country: gb, latitude: 54.598, longitude: -7.295)
Area.find_or_create_by(slug: :coolham__west_sussex).update(name: 'Coolham', country: gb, latitude: 50.99211, longitude: -0.42397)
Area.find_or_create_by(slug: :copplestone).update(name: 'Copplestone', country: gb)
Area.find_or_create_by(slug: :corbridge).update(name: 'Corbridge', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :corfe).update(name: 'Corfe', country: gb)
Area.find_or_create_by(slug: :corris).update(name: 'Corris', country: gb)
Area.find_or_create_by(slug: :corwen).update(name: 'Corwen', country: gb, latitude: 52.97967, longitude: -3.37439)
Area.find_or_create_by(slug: :coseley).update(name: 'Coseley', country: gb)
Area.find_or_create_by(slug: :cothal).update(name: 'Cothal', country: gb)
Area.find_or_create_by(slug: :cotherstone).update(name: 'Cotherstone', country: gb)
Area.find_or_create_by(slug: :cottered).update(name: 'Cottered', country: gb, latitude: 51.94592, longitude: -0.07732)
Area.find_or_create_by(slug: :cottingham).update(name: 'Cottingham', country: gb)
Area.find_or_create_by(slug: :coulsdon).update(name: 'Coulsdon', country: gb, latitude: 51.31835, longitude: -0.13556)
Area.find_or_create_by(slug: :countesthorpe).update(name: 'Countesthorpe', country: gb, latitude: 52.55389, longitude: -1.15522)
Area.find_or_create_by(slug: :coventry).update(name: 'Coventry', country: gb, latitude: 52.40897, longitude: -1.51993)
Area.find_or_create_by(slug: :cowan_bridge).update(name: 'Cowan Bridge', country: gb, latitude: 54.1842, longitude: -2.56191)
Area.find_or_create_by(slug: :cowbridge).update(name: 'Cowbridge', country: gb, latitude: 51.45949, longitude: -3.51231)
Area.find_or_create_by(slug: :cowes).update(name: 'Cowes', country: gb, latitude: 50.75691, longitude: -1.30196)
Area.find_or_create_by(slug: :coxwold).update(name: 'Coxwold', country: gb, latitude: 54.1886, longitude: -1.1874)
Area.find_or_create_by(slug: :cradley).update(name: 'Cradley', country: gb)
Area.find_or_create_by(slug: :craigellachie).update(name: 'Craigellachie', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :cranbrook).update(name: 'Cranbrook', country: gb, latitude: 51.09586, longitude: 0.53665)
Area.find_or_create_by(slug: :craster).update(name: 'Craster', country: gb)
Area.find_or_create_by(slug: :craven_arms).update(name: 'Craven Arms', country: gb, latitude: 52.44145, longitude: -2.84436)
Area.find_or_create_by(slug: :crawley).update(name: 'Crawley', country: gb, latitude: 51.1167, longitude: -0.1845)
Area.find_or_create_by(slug: :crayford).update(name: 'Crayford', country: gb)
Area.find_or_create_by(slug: :crediton).update(name: 'Crediton', country: gb, latitude: 50.79037, longitude: -3.65772)
Area.find_or_create_by(slug: :crewe).update(name: 'Crewe', country: gb, latitude: 53.09507, longitude: -2.44038)
Area.find_or_create_by(slug: :crewkerne).update(name: 'Crewkerne', country: gb, latitude: 50.88352, longitude: -2.79615)
Area.find_or_create_by(slug: :criccieth).update(name: 'Criccieth', country: gb)
Area.find_or_create_by(slug: :crich).update(name: 'Crich', country: gb, latitude: 53.0907, longitude: -1.48691)
Area.find_or_create_by(slug: :crickhowell).update(name: 'Crickhowell', country: gb, latitude: 51.86691, longitude: -3.12943)
Area.find_or_create_by(slug: :cricklade).update(name: 'Cricklade', country: gb, latitude: 51.64045, longitude: -1.8578)
Area.find_or_create_by(slug: :crieff).update(name: 'Crieff', country: gb, latitude: 56.3736, longitude: -3.83358)
Area.find_or_create_by(slug: :crockernwell).update(name: 'Crockernwell', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :crofton).update(name: 'Crofton', country: gb)
Area.find_or_create_by(slug: :cromarty).update(name: 'Cromarty', country: gb, latitude: 57.68002, longitude: -4.03063)
Area.find_or_create_by(slug: :cromer).update(name: 'Cromer', country: gb, latitude: 52.93123, longitude: 1.28838)
Area.find_or_create_by(slug: :cromford).update(name: 'Cromford', country: gb, latitude: 53.10549, longitude: -1.54005)
Area.find_or_create_by(slug: :crook).update(name: 'Crook', country: gb, latitude: 54.34447, longitude: -2.84734)
Area.find_or_create_by(slug: :crookham_village).update(name: 'Crookham Village', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :cropredy).update(name: 'Cropredy', country: gb, latitude: 52.11474, longitude: -1.32131)
Area.find_or_create_by(slug: :crossgar).update(name: 'Crossgar', country: gb, latitude: 54.39651, longitude: -5.75926)
Area.find_or_create_by(slug: :cross_roads).update(name: 'Cross Roads', country: gb)
Area.find_or_create_by(slug: :crowthorne).update(name: 'Crowthorne', country: gb, latitude: 51.368, longitude: -0.7945)
Area.find_or_create_by(slug: :croyde).update(name: 'Croyde', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :croydon).update(name: 'Croydon', country: gb, latitude: 51.39062, longitude: -0.09551)
Area.find_or_create_by(slug: :cruden_bay).update(name: 'Cruden Bay', country: gb)
Area.find_or_create_by(slug: :cudham).update(name: 'Cudham', country: gb, latitude: 51.3185, longitude: 0.0726)
Area.find_or_create_by(slug: :cullercoats).update(name: 'Cullercoats', country: gb, latitude: 55.03526, longitude: -1.43312)
Area.find_or_create_by(slug: :cupar).update(name: 'Cupar', country: gb)
Area.find_or_create_by(slug: :curbar).update(name: 'Curbar', country: gb, latitude: 53.26408, longitude: -1.61679)
Area.find_or_create_by(slug: :cushendun).update(name: 'Cushendun', country: gb, latitude: 55.12563, longitude: -6.04214)
Area.find_or_create_by(slug: :cwmaman).update(name: 'Cwmaman', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :cwmfelinfach).update(name: 'Cwmfelinfach', country: gb)

Area.find_or_create_by(slug: :dagenham).update(name: 'Dagenham', country: gb, latitude: 51.54354, longitude: 0.13084)
Area.find_or_create_by(slug: :dalbeattie).update(name: 'Dalbeattie', country: gb)
Area.find_or_create_by(slug: :dalkeith).update(name: 'Dalkeith', country: gb, latitude: 55.8921, longitude: -3.09984)
Area.find_or_create_by(slug: :dalmally).update(name: 'Dalmally', country: gb)
Area.find_or_create_by(slug: :dalton_in_furness).update(name: 'Dalton-In-Furness', country: gb, latitude: 54.15581, longitude: -3.18379)
Area.find_or_create_by(slug: :darlington).update(name: 'Darlington', country: gb, latitude: 54.53032, longitude: -1.55517)
Area.find_or_create_by(slug: :darnholm).update(name: 'Darnholm', country: gb)
Area.find_or_create_by(slug: :dartford).update(name: 'Dartford', country: gb, latitude: 51.44113, longitude: 0.21189)
Area.find_or_create_by(slug: :dartington).update(name: 'Dartington', country: gb, latitude: 50.4399, longitude: -3.69359)
Area.find_or_create_by(slug: :dartmouth).update(name: 'Dartmouth', country: gb, latitude: 50.34832, longitude: -3.57665)
Area.find_or_create_by(slug: :darwen).update(name: 'Darwen', country: gb, latitude: 53.68733, longitude: -2.46212)
Area.find_or_create_by(slug: :daventry).update(name: 'Daventry', country: gb, latitude: 52.26419, longitude: -1.18618)
Area.find_or_create_by(slug: :dawlish_warren).update(name: 'Dawlish Warren', country: gb, latitude: 50.68175, longitude: -3.24343)
Area.find_or_create_by(slug: :deal).update(name: 'Deal', country: gb, latitude: 51.22796, longitude: 1.40391)
Area.find_or_create_by(slug: :deanston).update(name: 'Deanston', country: gb, latitude: 56.19092, longitude: -4.0865)
Area.find_or_create_by(slug: :dedham).update(name: 'Dedham', country: gb, latitude: 51.94997, longitude: 0.99614)
Area.find_or_create_by(slug: :deganwy).update(name: 'Deganwy', country: gb, latitude: 53.29637, longitude: -3.835)
Area.find_or_create_by(slug: :denbigh).update(name: 'Denbigh', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :denham).update(name: 'Denham', country: gb, latitude: 51.5725, longitude: -0.4972)
Area.find_or_create_by(slug: :dent).update(name: 'Dent', country: gb, latitude: 54.27727, longitude: -2.45481)
Area.find_or_create_by(slug: :denton).update(name: 'Denton', country: gb, latitude: 53.4533, longitude: -2.11275)
Area.find_or_create_by(slug: :denver).update(name: 'Denver', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :derby).update(name: 'Derby', country: gb, latitude: 52.91947, longitude: -1.47164)
Area.find_or_create_by(slug: :dereham).update(name: 'Dereham', country: gb, latitude: 52.68125, longitude: 0.92791)
Area.find_or_create_by(slug: :deroran).update(name: 'Deroran', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :derrinraw).update(name: 'Derrinraw', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :derry).update(name: 'Derry', country: gb)
Area.find_or_create_by(slug: :derrytrasna).update(name: 'Derrytrasna', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :dervock).update(name: 'Dervock', country: gb, latitude: 55.12312, longitude: -6.47548)
Area.find_or_create_by(slug: :derwent).update(name: 'Derwent', country: gb)
Area.find_or_create_by(slug: :desford).update(name: 'Desford', country: gb)
Area.find_or_create_by(slug: :dethick).update(name: 'Dethick', country: gb, latitude: 53.12269, longitude: -1.51581)
Area.find_or_create_by(slug: :devauden).update(name: 'Devauden', country: gb)
Area.find_or_create_by(slug: :devizes).update(name: 'Devizes', country: gb, latitude: 51.34813, longitude: -1.99196)
Area.find_or_create_by(slug: :dewsbury).update(name: 'Dewsbury', country: gb, latitude: 53.68887, longitude: -1.62406)
Area.find_or_create_by(slug: :didcot).update(name: 'Didcot', country: gb, latitude: 51.611, longitude: -1.24271)
Area.find_or_create_by(slug: :didsbury).update(name: 'Didsbury', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :diggle).update(name: 'Diggle', country: gb, latitude: 53.56971, longitude: -1.99081)
Area.find_or_create_by(slug: :dilton_marsh).update(name: 'Dilton Marsh', country: gb, latitude: 51.24715, longitude: -2.21949)
Area.find_or_create_by(slug: :dingwall).update(name: 'Dingwall', country: gb, latitude: 57.59584, longitude: -4.42855)
Area.find_or_create_by(slug: :disley).update(name: 'Disley', country: gb)
Area.find_or_create_by(slug: :ditchling).update(name: 'Ditchling', country: gb, latitude: 50.922, longitude: -0.11483)
Area.find_or_create_by(slug: :doddiscombesleigh).update(name: 'Doddiscombesleigh', country: gb, latitude: 50.67096, longitude: -3.66135)
Area.find_or_create_by(slug: :donaghadee).update(name: 'Donaghadee', country: gb, latitude: 54.64152, longitude: -5.53295)
Area.find_or_create_by(slug: :doncaster).update(name: 'Doncaster', country: gb, latitude: 53.49908, longitude: -1.05586)
Area.find_or_create_by(slug: :donington).update(name: 'Donington', country: gb, latitude: 52.90445, longitude: -0.20581)
Area.find_or_create_by(slug: :donisthorpe).update(name: 'Donisthorpe', country: gb)
Area.find_or_create_by(slug: :donnington).update(name: 'Donnington', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :dorchester).update(name: 'Dorchester', country: gb, latitude: 50.71469, longitude: -2.43734)
Area.find_or_create_by(slug: :dorking).update(name: 'Dorking', country: gb, latitude: 51.23326, longitude: -0.33098)
Area.find_or_create_by(slug: :dornoch).update(name: 'Dornoch', country: gb)
Area.find_or_create_by(slug: :dorsington).update(name: 'Dorsington', country: gb)
Area.find_or_create_by(slug: :doune).update(name: 'Doune', country: gb, latitude: 56.18879, longitude: -4.06436)
Area.find_or_create_by(slug: :doune_isle_of_lewis).update(name: 'Doune, Isle of Lewis', country: gb)
Area.find_or_create_by(slug: :dovedale).update(name: 'Dovedale', country: gb, latitude: 53.05618, longitude: -1.78226)
Area.find_or_create_by(slug: :dover).update(name: 'Dover', country: gb, latitude: 51.12824, longitude: 1.31985)
Area.find_or_create_by(slug: :dowlais).update(name: 'Dowlais', country: gb)
Area.find_or_create_by(slug: :downe_village_orpington).update(name: 'Downe Village, Orpington', country: gb)
Area.find_or_create_by(slug: :downham).update(name: 'Downham', country: gb, latitude: 53.89444, longitude: -2.32893)
Area.find_or_create_by(slug: :downham_market).update(name: 'Downham Market', country: gb, latitude: 52.60275, longitude: 0.37532)
Area.find_or_create_by(slug: :downpatrick).update(name: 'Downpatrick', country: gb, latitude: 54.3265, longitude: -5.7183)
Area.find_or_create_by(slug: :drayton).update(name: 'Drayton', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :drayton_st_leonard).update(name: 'Drayton St Leonard', country: gb)
Area.find_or_create_by(slug: :droitwich_spa).update(name: 'Droitwich Spa', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :dromore).update(name: 'Dromore', country: gb, latitude: 54.39929, longitude: -6.15007)
Area.find_or_create_by(slug: :droxford).update(name: 'Droxford', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :droylsden).update(name: 'Droylsden', country: gb, latitude: 53.47933, longitude: -2.15225)
Area.find_or_create_by(slug: :drungewick).update(name: 'Drungewick', country: gb)
Area.find_or_create_by(slug: :dublin).update(name: 'Dublin', country: gb)
Area.find_or_create_by(slug: :dudley).update(name: 'Dudley', country: gb, latitude: 52.49408, longitude: -2.08563)
Area.find_or_create_by(slug: :dufftown).update(name: 'Dufftown', country: gb, latitude: 57.44794, longitude: -3.14695)
Area.find_or_create_by(slug: :dugland_hill).update(name: 'Dugland Hill', country: gb)
Area.find_or_create_by(slug: :dukinfield).update(name: 'Dukinfield', country: gb, latitude: 53.47522, longitude: -2.08902)
Area.find_or_create_by(slug: :dulwich).update(name: 'Dulwich', country: gb)
Area.find_or_create_by(slug: :dumbarton).update(name: 'Dumbarton', country: gb, latitude: 55.94331, longitude: -4.57127)
Area.find_or_create_by(slug: :dumfries).update(name: 'Dumfries', country: gb, latitude: 55.06972, longitude: -3.60913)
Area.find_or_create_by(slug: :dunbar).update(name: 'Dunbar', country: gb, latitude: 55.99759, longitude: -2.53955)
Area.find_or_create_by(slug: :dunbeath).update(name: 'Dunbeath', country: gb)
Area.find_or_create_by(slug: :dunblane).update(name: 'Dunblane', country: gb, latitude: 56.18727, longitude: -3.9642)
Area.find_or_create_by(slug: :dunchurch).update(name: 'Dunchurch', country: gb, latitude: 52.33329, longitude: -1.31866)
Area.find_or_create_by(slug: :duncton).update(name: 'Duncton', country: gb)
Area.find_or_create_by(slug: :dundee).update(name: 'Dundee', country: gb, latitude: 56.46383, longitude: -2.96228)
Area.find_or_create_by(slug: :dundonald).update(name: 'Dundonald', country: gb, latitude: 54.59513, longitude: -5.79028)
Area.find_or_create_by(slug: :dunfermline).update(name: 'Dunfermline', country: gb, latitude: 56.07087, longitude: -3.46363)
Area.find_or_create_by(slug: :dungannon).update(name: 'Dungannon', country: gb, latitude: 54.5036, longitude: -6.77027)
Area.find_or_create_by(slug: :dunham_town).update(name: 'Dunham Town', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :dunkeld).update(name: 'Dunkeld', country: gb)
Area.find_or_create_by(slug: :dunkeswell).update(name: 'Dunkeswell', country: gb)
Area.find_or_create_by(slug: :dunmurry).update(name: 'Dunmurry', country: gb, latitude: 54.54929, longitude: -6.00841)
Area.find_or_create_by(slug: :dunoon).update(name: 'Dunoon', country: gb)
Area.find_or_create_by(slug: :dunsop_bridge).update(name: 'Dunsop Bridge', country: gb, latitude: 53.94569, longitude: -2.51836)
Area.find_or_create_by(slug: :dunstable).update(name: 'Dunstable', country: gb, latitude: 51.88968, longitude: -0.52599)
Area.find_or_create_by(slug: :dunster).update(name: 'Dunster', country: gb, latitude: 51.18178, longitude: -3.44667)
Area.find_or_create_by(slug: :durham).update(name: 'Durham', country: gb, latitude: 54.77633, longitude: -1.57372)
Area.find_or_create_by(slug: :durness).update(name: 'Durness', country: gb, latitude: 58.56856, longitude: -4.75382)
Area.find_or_create_by(slug: :dursley).update(name: 'Dursley', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :duval).update(name: 'Duval', country: gb, latitude: 49.41767, longitude: -2.38129)
Area.find_or_create_by(slug: :dymchurch).update(name: 'Dymchurch', country: gb, latitude: 51.02964, longitude: 1.00144)
Area.find_or_create_by(slug: :ealing).update(name: 'Ealing', country: gb, latitude: 51.52506, longitude: -0.40239)
Area.find_or_create_by(slug: :earby).update(name: 'Earby', country: gb, latitude: 53.91808, longitude: -2.1306)
Area.find_or_create_by(slug: :earlsferry).update(name: 'Earlsferry', country: gb, latitude: 56.18856, longitude: -2.8351)
Area.find_or_create_by(slug: :earl_shilton).update(name: 'Earl Shilton', country: gb, latitude: 52.5752, longitude: -1.33181)
Area.find_or_create_by(slug: :earl_sterndale).update(name: 'Earl Sterndale', country: gb, latitude: 53.19643, longitude: -1.87721)
Area.find_or_create_by(slug: :earnley).update(name: 'Earnley', country: gb, latitude: 50.76394, longitude: -0.8438)
Area.find_or_create_by(slug: :eartham).update(name: 'Eartham', country: gb, latitude: 50.87605, longitude: -0.66677)
Area.find_or_create_by(slug: :easebourne).update(name: 'Easebourne', country: gb)
Area.find_or_create_by(slug: :eastbourne).update(name: 'Eastbourne', country: gb, latitude: 50.76926, longitude: 0.26734)
Area.find_or_create_by(slug: :east_budleigh).update(name: 'East Budleigh', country: gb)
Area.find_or_create_by(slug: :east_dean).update(name: 'East Dean', country: gb, latitude: 50.759, longitude: 0.20569)
Area.find_or_create_by(slug: :east_dereham).update(name: 'East Dereham', country: gb)
Area.find_or_create_by(slug: :east_farleigh).update(name: 'East Farleigh', country: gb)
Area.find_or_create_by(slug: :east_fortune).update(name: 'East Fortune', country: gb)
Area.find_or_create_by(slug: :eastgrinstead).update(name: 'East Grinstead', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :eastham).update(name: 'Eastham', country: gb)
Area.find_or_create_by(slug: :east_hendred).update(name: 'East Hendred', country: gb, latitude: 50.68175, longitude: -3.24343)
Area.find_or_create_by(slug: :east_hoathly).update(name: 'East Hoathly', country: gb, latitude: 50.9254, longitude: 0.1647)
Area.find_or_create_by(slug: :eastkilbride).update(name: 'East Kilbride', country: gb, latitude: 55.77658, longitude: -4.14855)
Area.find_or_create_by(slug: :east_leake).update(name: 'East Leake', country: gb, latitude: 52.83484, longitude: -1.17993)
Area.find_or_create_by(slug: :eastleigh).update(name: 'Eastleigh', country: gb, latitude: 50.96573, longitude: -1.35395)
Area.find_or_create_by(slug: :east_meon).update(name: 'East Meon', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :east_preston).update(name: 'East Preston', country: gb, latitude: 50.80529, longitude: -0.48588)
Area.find_or_create_by(slug: :east_wemyss).update(name: 'East Wemyss', country: gb)
Area.find_or_create_by(slug: :eastwood).update(name: 'Eastwood', country: gb, latitude: 53.01857, longitude: -1.30694)
Area.find_or_create_by(slug: :eaton).update(name: 'Eaton', country: gb)
Area.find_or_create_by(slug: :ecclefechan).update(name: 'Ecclefechan', country: gb, latitude: 55.05919, longitude: -3.26413)
Area.find_or_create_by(slug: :eccles).update(name: 'Eccles', country: gb, latitude: 53.48425, longitude: -2.33681)
Area.find_or_create_by(slug: :edgworth).update(name: 'Edgworth', country: gb, latitude: 53.64312, longitude: -2.39414)
Area.find_or_create_by(slug: :edinburgh).update(name: 'Edinburgh', country: gb, latitude: 55.94961, longitude: -3.19368)
Area.find_or_create_by(slug: :edmondthorpe).update(name: 'Edmondthorpe', country: gb)
Area.find_or_create_by(slug: :ednam).update(name: 'Ednam', country: gb, latitude: 55.62797, longitude: -2.41867)
Area.find_or_create_by(slug: :edwinstowe).update(name: 'Edwinstowe', country: gb)
Area.find_or_create_by(slug: :egham).update(name: 'Egham', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :elgin).update(name: 'Elgin', country: gb)
Area.find_or_create_by(slug: :ellesmere_port).update(name: 'Ellesmere Port', country: gb, latitude: 53.28777, longitude: -2.89239)
Area.find_or_create_by(slug: :elmton).update(name: 'Elmton', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :elstow).update(name: 'Elstow', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :elsworth).update(name: 'Elsworth', country: gb)
Area.find_or_create_by(slug: :elton).update(name: 'Elton', country: gb, latitude: 53.14463, longitude: -1.66781)
Area.find_or_create_by(slug: :ely).update(name: 'Ely', country: gb, latitude: 52.39296, longitude: 0.20537)
Area.find_or_create_by(slug: :emsworth).update(name: 'Emsworth', country: gb, latitude: 50.8505, longitude: -0.9473)
Area.find_or_create_by(slug: :emyvale).update(name: 'Emyvale', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :enderby).update(name: 'Enderby', country: gb, latitude: 52.58871, longitude: -1.2151)
Area.find_or_create_by(slug: :enfield).update(name: 'Enfield', country: gb, latitude: 51.65837, longitude: -0.0997)
Area.find_or_create_by(slug: :enniskillen).update(name: 'Enniskillen', country: gb, latitude: 54.34908, longitude: -7.64376)
Area.find_or_create_by(slug: :enstone).update(name: 'Enstone', country: gb, latitude: 51.9149, longitude: -1.45229)
Area.find_or_create_by(slug: :epping).update(name: 'Epping', country: gb, latitude: 51.69382, longitude: 0.11385)
Area.find_or_create_by(slug: :epsom).update(name: 'Epsom', country: gb, latitude: 51.32149, longitude: -0.25851)
Area.find_or_create_by(slug: :erddig).update(name: 'Erddig', country: gb, latitude: 53.02665, longitude: -3.00587)
Area.find_or_create_by(slug: :esher).update(name: 'Esher', country: gb, latitude: 51.37714, longitude: -0.35647)
Area.find_or_create_by(slug: :eskdale).update(name: 'Eskdale', country: gb, latitude: 54.39031, longitude: -3.32034)
Area.find_or_create_by(slug: :eton).update(name: 'Eton', country: gb, latitude: 51.49048, longitude: -0.60988)
Area.find_or_create_by(slug: :etton).update(name: 'Etton', country: gb, latitude: 53.87836, longitude: -0.51282)
Area.find_or_create_by(slug: :ettrick).update(name: 'Ettrick', country: gb)
Area.find_or_create_by(slug: :eversholt).update(name: 'Eversholt', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :evesham).update(name: 'Evesham', country: gb)
Area.find_or_create_by(slug: :ewell).update(name: 'Ewell', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :exbury).update(name: 'Exbury', country: gb, latitude: 50.79219, longitude: -1.40543)
Area.find_or_create_by(slug: :exeter).update(name: 'Exeter', country: gb, latitude: 50.72173, longitude: -3.52922)
Area.find_or_create_by(slug: :exmouth).update(name: 'Exmouth', country: gb, latitude: 50.61799, longitude: -3.41165)
Area.find_or_create_by(slug: :eyam).update(name: 'Eyam', country: gb, latitude: 53.28422, longitude: -1.67568)
Area.find_or_create_by(slug: :eyemouth).update(name: 'Eyemouth', country: gb, latitude: 55.87195, longitude: -2.08923)
Area.find_or_create_by(slug: :eynesbury).update(name: 'Eynesbury', country: gb, latitude: 52.21982, longitude: -0.26842)
Area.find_or_create_by(slug: :failsworth).update(name: 'Failsworth', country: gb)
Area.find_or_create_by(slug: :fairford).update(name: 'Fairford', country: gb, latitude: 51.70805, longitude: -1.78314)
Area.find_or_create_by(slug: :fair_isle).update(name: 'Fair Isle', country: gb, latitude: 59.5144, longitude: -1.64786)
Area.find_or_create_by(slug: :falkirk).update(name: 'Falkirk', country: gb, latitude: 56.00079, longitude: -3.81719)
Area.find_or_create_by(slug: :falmouth).update(name: 'Falmouth', country: gb, latitude: 50.15386, longitude: -5.06507)
Area.find_or_create_by(slug: :fareham).update(name: 'Fareham', country: gb, latitude: 50.85434, longitude: -1.17369)
Area.find_or_create_by(slug: :faringdon).update(name: 'Faringdon', country: gb, latitude: 51.65853, longitude: -1.5713)
Area.find_or_create_by(slug: :farnborough_hampshire).update(name: 'Farnborough, Hampshire', country: gb, latitude: 51.28873, longitude: -0.75772)
Area.find_or_create_by(slug: :farnborough_kent).update(name: 'Farnborough, Kent', country: gb, latitude: 51.3532, longitude: 0.07512)
Area.find_or_create_by(slug: :farnham).update(name: 'Farnham', country: gb, latitude: 51.21698, longitude: -0.79615)
Area.find_or_create_by(slug: :farningham).update(name: 'Farningham', country: gb)
Area.find_or_create_by(slug: :farnworth).update(name: 'Farnworth', country: gb, latitude: 53.54063, longitude: -2.40253)
Area.find_or_create_by(slug: :farringdon).update(name: 'Farringdon', country: gb)
Area.find_or_create_by(slug: :farrington_gurney).update(name: 'Farrington Gurney', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :faversham).update(name: 'Faversham', country: gb, latitude: 51.31636, longitude: 0.89224)
Area.find_or_create_by(slug: :felindre_farchog).update(name: 'Felindre Farchog', country: gb)
Area.find_or_create_by(slug: :felpham).update(name: 'Felpham', country: gb)
Area.find_or_create_by(slug: :ferndale).update(name: 'Ferndale', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :ferryhill).update(name: 'Ferryhill', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :fife).update(name: 'Fife', country: gb)
Area.find_or_create_by(slug: :filey).update(name: 'Filey', country: gb, latitude: 54.20722, longitude: -0.28597)
Area.find_or_create_by(slug: :filkins).update(name: 'Filkins', country: gb, latitude: 51.73673, longitude: -1.65706)
Area.find_or_create_by(slug: :finchingfield).update(name: 'Finchingfield', country: gb)
Area.find_or_create_by(slug: :findern).update(name: 'Findern', country: gb, latitude: 52.87699, longitude: -1.54483)
Area.find_or_create_by(slug: :finstock).update(name: 'Finstock', country: gb, latitude: 51.84407, longitude: -1.48166)
Area.find_or_create_by(slug: :fishguard).update(name: 'Fishguard', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :fittleworth).update(name: 'Fittleworth', country: gb)
Area.find_or_create_by(slug: :flamborough).update(name: 'Flamborough', country: gb, latitude: 54.11424, longitude: -0.11416)
Area.find_or_create_by(slug: :fleetwood).update(name: 'Fleetwood', country: gb, latitude: 50.68175, longitude: -3.24343)
Area.find_or_create_by(slug: :flint).update(name: 'Flint', country: gb)
Area.find_or_create_by(slug: :flotterstone).update(name: 'Flotterstone', country: gb, latitude: 55.8611, longitude: -3.26015)
Area.find_or_create_by(slug: :fodderletter).update(name: 'Fodderletter', country: gb)
Area.find_or_create_by(slug: :folkestone).update(name: 'Folkestone', country: gb, latitude: 51.07692, longitude: 1.16846)
Area.find_or_create_by(slug: :fordingbridge).update(name: 'Fordingbridge', country: gb, latitude: 50.92673, longitude: -1.7903)
Area.find_or_create_by(slug: :forfar).update(name: 'Forfar', country: gb, latitude: 56.64608, longitude: -2.87973)
Area.find_or_create_by(slug: :formby).update(name: 'Formby', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :fort_william).update(name: 'Fort William', country: gb, latitude: 56.81974, longitude: -5.10332)
Area.find_or_create_by(slug: :fort_worth).update(name: 'Fort Worth', country: gb)
Area.find_or_create_by(slug: :foulby).update(name: 'Foulby', country: gb, latitude: 53.65505, longitude: -1.39963)
Area.find_or_create_by(slug: :fowey).update(name: 'Fowey', country: gb, latitude: 50.33629, longitude: -4.65161)
Area.find_or_create_by(slug: :foxton).update(name: 'Foxton', country: gb, latitude: 52.50109, longitude: -0.9825)
Area.find_or_create_by(slug: :fraddon).update(name: 'Fraddon', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :fradley).update(name: 'Fradley', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :framlingham).update(name: 'Framlingham', country: gb, latitude: 52.22449, longitude: 1.34689)
Area.find_or_create_by(slug: :fraserburgh).update(name: 'Fraserburgh', country: gb, latitude: 57.69138, longitude: -2.00508)
Area.find_or_create_by(slug: :freshwater_bay).update(name: 'Freshwater Bay', country: gb, latitude: 50.6724, longitude: -1.51607)
Area.find_or_create_by(slug: :frieth).update(name: 'Frieth', country: gb)
Area.find_or_create_by(slug: :frinton_on_sea).update(name: 'Frinton-on-Sea', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :frittenden).update(name: 'Frittenden', country: gb, latitude: 51.475, longitude: 0.0)
Area.find_or_create_by(slug: :frodsham).update(name: 'Frodsham', country: gb, latitude: 50.68175, longitude: -3.24343)
Area.find_or_create_by(slug: :frome).update(name: 'Frome', country: gb, latitude: 51.2301, longitude: -2.32097)
Area.find_or_create_by(slug: :fulking).update(name: 'Fulking', country: gb)
