Language.find_or_create_by(alpha2: :af).update(name: 'Afrikaans')
Language.find_or_create_by(alpha2: 'af-en').update(name: 'Afrikaans and English')
Language.find_or_create_by(alpha2: :be).update(name: 'Belarusian')
Language.find_or_create_by(alpha2: :bg).update(name: 'Bulgarian')
Language.find_or_create_by(alpha2: :ca).update(name: 'Catalan')
Language.find_or_create_by(alpha2: :cs).update(name: 'Czech')
Language.find_or_create_by(alpha2: :cy).update(name: 'Welsh')
Language.find_or_create_by(alpha2: 'cy-en').update(name: 'Welsh and English')
Language.find_or_create_by(alpha2: :da).update(name: 'Danish')
Language.find_or_create_by(alpha2: :de).update(name: 'German')
Language.find_or_create_by(alpha2: 'de-en').update(name: 'German and English')
Language.find_or_create_by(alpha2: :dero).update(name: 'German and Romanian')
Language.find_or_create_by(alpha2: :en).update(name: 'English')
Language.find_or_create_by(alpha2: :eo).update(name: 'Esperanto')
Language.find_or_create_by(alpha2: :es).update(name: 'Spanish')
Language.find_or_create_by(alpha2: 'eu-es').update(name: 'Basque and Spanish')
Language.find_or_create_by(alpha2: :fi).update(name: 'Finnish')
Language.find_or_create_by(alpha2: :fl).update(name: 'Filipino')
Language.find_or_create_by(alpha2: :fr).update(name: 'French')
Language.find_or_create_by(alpha2: :fren).update(name: 'French & English')
Language.find_or_create_by(alpha2: :ga).update(name: 'Irish')
Language.find_or_create_by(alpha2: 'ga-en').update(name: 'Irish & English')
Language.find_or_create_by(alpha2: :gr).update(name: 'Greek')
Language.find_or_create_by(alpha2: :hu).update(name: 'Hungarian')
Language.find_or_create_by(alpha2: 'hu-se').update(name: 'Hungarian and Swedish')
Language.find_or_create_by(alpha2: :hy).update(name: 'Armenian')
Language.find_or_create_by(alpha2: :it).update(name: 'Italian')
Language.find_or_create_by(alpha2: :ja).update(name: 'Japanese')
Language.find_or_create_by(alpha2: :ka).update(name: 'Georgian')
Language.find_or_create_by(alpha2: :ko).update(name: 'Korean')
Language.find_or_create_by(alpha2: :la).update(name: 'Latin')
Language.find_or_create_by(alpha2: :lt).update(name: 'Lithuanian')
Language.find_or_create_by(alpha2: :ms).update(name: 'Malay')
Language.find_or_create_by(alpha2: :mt).update(name: 'Maltese')
Language.find_or_create_by(alpha2: 'my-en').update(name: 'Burmese and English')
Language.find_or_create_by(alpha2: :nl).update(name: 'Dutch')
Language.find_or_create_by(alpha2: :no).update(name: 'Norwegian')
Language.find_or_create_by(alpha2: :oc).update(name: 'Occitan')
Language.find_or_create_by(alpha2: :pl).update(name: 'Polish')
Language.find_or_create_by(alpha2: 'pl-en-de-ru').update(name: 'Polish, English, German & Russian')
Language.find_or_create_by(alpha2: :pt).update(name: 'Portuguese')
Language.find_or_create_by(alpha2: :ru).update(name: 'Russian')
Language.find_or_create_by(alpha2: :se).update(name: 'Swedish')
Language.find_or_create_by(alpha2: 'se-en').update(name: 'Swedish and English')
Language.find_or_create_by(alpha2: :sl).update(name: 'Slovene')
Language.find_or_create_by(alpha2: 'sl-cs-de').update(name: 'Slovene, Czech and German')
Language.find_or_create_by(alpha2: :sq).update(name: 'Albanian')
Language.find_or_create_by(alpha2: :tr).update(name: 'Turkish')
Language.find_or_create_by(alpha2: :tt).update(name: 'Tatar')
Language.find_or_create_by(alpha2: :ua).update(name: 'Ukrainian')
Language.find_or_create_by(alpha2: 'uk-lt').update(name: 'Ukranian and Lithuanian')
Language.find_or_create_by(alpha2: :vi).update(name: 'Vietnamese')
Language.find_or_create_by(alpha2: :zh).update(name: 'Chinese')
Language.find_or_create_by(alpha2: 'zh-TW').update(name: 'Chinese (Traditional)')
