Language.find_or_create_by(abbreviation: 'All Rights Reserved').update(allows_commercial_use: false, name: 'All Rights Reserved', url: 'http://en.wikipedia.org/wiki/All_rights_reserved')
Language.find_or_create_by(abbreviation: 'CC0').update(allows_commercial_use: true, name: 'Public Domain Dedication', url: 'http://creativecommons.org/publicdomain/zero/1.0/')
Language.find_or_create_by(abbreviation: 'CC BY 2.0').update(allows_commercial_use: true, name: 'Attribution 2.0 Generic', url: 'http://creativecommons.org/licenses/by/2.0/')
Language.find_or_create_by(abbreviation: 'CC BY 2.0 de').update(allows_commercial_use: true, name: 'Namensnennung 2.0 Deutschland', url: 'http://creativecommons.org/licenses/by/2.0/de/deed.en/')
Language.find_or_create_by(abbreviation: 'CC BY 2.0 uk').update(allows_commercial_use: true, name: 'Attribution 2.0 Generic', url: 'http://creativecommons.org/licenses/by/2.0/uk/deed.en/')
Language.find_or_create_by(abbreviation: 'CC BY 2.5').update(allows_commercial_use: true, name: 'Attribution 2.5 Generic', url: 'http://creativecommons.org/licenses/by/2.5/')
Language.find_or_create_by(abbreviation: 'CC BY 3.0').update(allows_commercial_use: true, name: 'Attribution 3.0 Unported', url: 'http://creativecommons.org/licenses/by/3.0/')
Language.find_or_create_by(abbreviation: 'CC BY 3.0 br').update(allows_commercial_use: true, name: 'Atribuição 3.0 Brasil', url: 'http://creativecommons.org/licenses/by/3.0/br/deed.en/')
Language.find_or_create_by(abbreviation: 'CC BY 4.0').update(allows_commercial_use: true, name: 'Attribution 4.0 International', url: 'http://creativecommons.org/licenses/by/4.0/')
Language.find_or_create_by(abbreviation: 'CC BY-NC 2.0').update(allows_commercial_use: false, name: 'Attribution-NonCommercial 2.0 Generic', url: 'http://creativecommons.org/licenses/by-nc/2.0/')
Language.find_or_create_by(abbreviation: 'CC BY-NC-ND 2.0').update(allows_commercial_use: false, name: 'Attribution-NonCommercial-NoDerivs 2.0 Generic', url: 'http://creativecommons.org/licenses/by-nc-nd/2.0/')
Language.find_or_create_by(abbreviation: 'CC BY-NC-SA 2.0').update(allows_commercial_use: false, name: 'Attribution-NonCommercial-ShareAlike 2.0 Generic', url: 'http://creativecommons.org/licenses/by-nc-sa/2.0/')
Language.find_or_create_by(abbreviation: 'CC BY-ND 2.0').update(allows_commercial_use: true, name: 'Attribution-NoDerivs 2.0 Generic', url: 'http://creativecommons.org/licenses/by-nd/2.0/')
Language.find_or_create_by(abbreviation: 'CC BY-SA 1.0').update(allows_commercial_use: true, name: 'Attribution-ShareAlike 1.0 Generic', url: 'http://creativecommons.org/licenses/by-sa/1.0/')
Language.find_or_create_by(abbreviation: 'CC BY-SA 2.0').update(allows_commercial_use: true, name: 'Attribution-ShareAlike 2.0 Generic', url: 'http://creativecommons.org/licenses/by-sa/2.0/')
Language.find_or_create_by(abbreviation: 'CC BY-SA 2.0 de').update(allows_commercial_use: true, name: 'Attribution 2.0 Generic', url: 'http://creativecommons.org/licenses/by-sa/2.0/de/deed.en/')
Language.find_or_create_by(abbreviation: 'CC BY-SA 2.0 uk').update(allows_commercial_use: true, name: 'Attribution 2.0 UK: England & Wales', url: 'http://creativecommons.org/licenses/by-sa/2.0/uk/deed.en/')
Language.find_or_create_by(abbreviation: 'CC BY-SA 2.5').update(allows_commercial_use: true, name: 'Attribution-ShareAlike 2.5 Generic', url: 'http://creativecommons.org/licenses/by-sa/2.5/')
Language.find_or_create_by(abbreviation: 'CC BY-SA 2.5-2.0-1.0').update(allows_commercial_use: true, name: 'CC BY-SA 2.5-2.0-1.0', url: 'http://creativecommons.org/licenses/by-sa/2.5-2.0-1.0/')
Language.find_or_create_by(abbreviation: 'CC BY-SA 3.0').update(allows_commercial_use: true, name: 'Attribution-ShareAlike 3.0 Unported', url: 'http://creativecommons.org/licenses/by-sa/3.0/')
Language.find_or_create_by(abbreviation: 'CC BY-SA 3.0 au').update(allows_commercial_use: true, name: 'Attribution-ShareAlike 3.0 Australia', url: 'http://creativecommons.org/licenses/by-sa/3.0/au/deed.en/')
Language.find_or_create_by(abbreviation: 'CC BY-SA 3.0 de').update(allows_commercial_use: true, name: 'Namensnennung - Weitergabe unter gleichen Bedingungen 3.0 Deutschland', url: 'http://creativecommons.org/licenses/by-sa/3.0/de/deed.en/')
Language.find_or_create_by(abbreviation: 'CC BY-SA 3.0 nl').update(allows_commercial_use: true, name: 'Naamsvermelding-GelijkDelen 3.0 Nederland', url: 'http://creativecommons.org/licenses/by-sa/3.0/nl/deed.en/')
Language.find_or_create_by(abbreviation: 'CC BY-SA 4.0').update(allows_commercial_use: true, name: 'Attribution-ShareAlike 4.0 International', url: 'http://creativecommons.org/licenses/by-sa/4.0/')
Language.find_or_create_by(abbreviation: 'FAL').update(allows_commercial_use: true, name: 'Free Art License 1.3', url: 'http://artlibre.org/licence/lal/en/')
Language.find_or_create_by(abbreviation: 'GFDL').update(allows_commercial_use: true, name: 'GNU Free Documentation License', url: 'http://www.gnu.org/copyleft/fdl.html/')
Language.find_or_create_by(abbreviation: 'GFDL 1.2').update(allows_commercial_use: true, name: 'GNU Free Documentation License 1.2', url: 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.html')
Language.find_or_create_by(abbreviation: 'None known').update(allows_commercial_use: true, name: 'No known copyright restrictions', url: 'http://www.flickr.com/commons/usage/')
Language.find_or_create_by(abbreviation: 'OGL').update(allows_commercial_use: true, name: 'UK Open Government Licence', url: 'http://www.nationalarchives.gov.uk/doc/open-government-licence/version/1/')
Language.find_or_create_by(abbreviation: 'PD').update(allows_commercial_use: true, name: 'Assumed public domain', url: 'https://en.wikipedia.org/wiki/Public_domain')
Language.find_or_create_by(abbreviation: 'PD 1.0').update(allows_commercial_use: true, name: 'Public Domain Mark 1.0', url: 'http://creativecommons.org/publicdomain/mark/1.0/')
Language.find_or_create_by(abbreviation: 'USA GOV').update(allows_commercial_use: true, name: 'United States Government Work', url: 'http://www.usa.gov/copyright.shtml')
