# the top 30 verbs...
Verb.find_or_create_by(name: "lived")
Verb.find_or_create_by(name: "sited")
Verb.find_or_create_by(name: "was")
Verb.find_or_create_by(name: "worked")
Verb.find_or_create_by(name: "was born")
Verb.find_or_create_by(name: "designed")
Verb.find_or_create_by(name: "built")
Verb.find_or_create_by(name: "stayed")
Verb.find_or_create_by(name: "lived near")
Verb.find_or_create_by(name: "died")
Verb.find_or_create_by(name: "visited")
Verb.find_or_create_by(name: "played")
Verb.find_or_create_by(name: "performed")
Verb.find_or_create_by(name: "was buried")
Verb.find_or_create_by(name: "was born near")
Verb.find_or_create_by(name: "founded")
Verb.find_or_create_by(name: "is commemorated")
Verb.find_or_create_by(name: "attended school")
Verb.find_or_create_by(name: "owned")
Verb.find_or_create_by(name: "died near")
Verb.find_or_create_by(name: "studied")
Verb.find_or_create_by(name: "was killed")
Verb.find_or_create_by(name: "donated")
Verb.find_or_create_by(name: "opened")
Verb.find_or_create_by(name: "preached")
Verb.find_or_create_by(name: "worshipped")
Verb.find_or_create_by(name: "taught")
Verb.find_or_create_by(name: "worked near")
Verb.find_or_create_by(name: "was founded")
Verb.find_or_create_by(name: "was near")
