name: Lint Markdown
on: [push, pull_request, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: '**/*.md'
